apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    dew.ms/git-commit: '0001'
    dew.ms/scm-url: ''
  labels:
    app: helloworld-frontend
    provider: dew
    version: '0001'
    group: ms.dew.devops.it
  name: helloworld-frontend
  namespace: dew-test
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: helloworld-frontend
      group: ms.dew.devops.it
  template:
    metadata:
      annotations:
        dew.ms/git-commit: '0001'
        dew.ms/scm-url: ''
      labels:
        app: helloworld-frontend
        provider: dew
        version: '0001'
        group: ms.dew.devops.it
    spec:
      containers:
      - image: harbor.trc.com/dew-test/helloworld-frontend:0001
        imagePullPolicy: IfNotPresent
        name: dew-app
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        resources:
          limits: {}
          requests: {}
      nodeSelector:
        group: app
