[glossary]
== 术语

[glossary]
微服务(Microservices)::
    一种软体架构风格，它是以专注于单一责任与功能的小型功能区块 (Small Building Blocks) 为基础，利用模组化的方式组合出复杂的大型应用程式，各功能区块使用与语言无关 (Language-Independent/Language agnostic)的 API 集相互通讯。微服务架构运用于软体架构风格的其中一项概念是甘露运算 (Dew Computing)，意指由许多的小露水 (代表微服务的功能元件) 汇集而成的运算能力。
    (https://zh.wikipedia.org/wiki/%E5%BE%AE%E6%9C%8D%E5%8B%99)

组件与模块(Component & Module)::
    本文约定`组件`是一组业务功能封装成的jar包，可以独立运行，`模块`是一种包含特定技术功能封装成的jar包，不可以独立运行，一个`组件`往往包含多个`模块`。

服务网关(Service Gateway)::
  为各组件提供统一的外部访问接口，从而隐藏从客户端访问服务的复杂性，提高了客户端和服务访问组件的重用性。客户端不直接引用服务，因此不受任何实现细节和服务位置的影响。将服务访问逻辑封装到一个单独的层中还会提高访问逻辑的重用性，因为只要使用相同的传输和验证机制，就能为多个服务调用所使用。
  (https://msdn.microsoft.com/zh-cn/library/ff650101.aspx)

Zuul与F5::
  Zuul是Netflix开源的与Spring Cloud深度整合的服务网关，F5是一家应用交付网络(ADN)领域的领头公司，其下包含众多相关产品，其中也包含了实现服务网关的能力。

Maven::
  项目管理及自动构建工具，由Apache软件基金会所提供。基于项目对象模型（缩写：POM）概念，Maven利用一个中央信息片断能管理一个项目的构建、报告和文档等步骤。

Git与GitLab::
  分散式版本控制软件，与CVS、Subversion一类的集中式版本控制工具不同，它采用了分布式版本库的作法，不需要服务器端软件，就可以运作版本控制，使得源代码的发布和交流极其方便。Git的速度很快，这对于诸如Linux内核这样的大项目来说自然很重要。Git最为出色的是它的合并追踪（merge tracing）能力。
  GitLab是免费开源的Git托管工具，与GitHub不同，它即有类似的SAAS平台，也可以下载后独立部署。

DevOps::
  一种重视“软件开发人员（Dev）”和“IT运维技术人员（Ops）”之间沟通合作的文化、运动或惯例。透过自动化“软件交付”和“架构变更”的流程，来使得构建、测试、发布软件能够更加地快捷、频繁和可靠。

CI(Continuous Integration)与CD(Continuous Delivery)::
  一种软体工程手法，让软体产品的产出过程在一个短周期内完成，以保证软体可以稳定、持续的保持在随时可以释出的状况。它的目标在于让软体的建置、测试与释出变得更快以及更频繁。这种方式可以减少软体开发的成本与时间，减少风险。


