[[framework-best-practices]]
=== 框架最佳实践

==== 项目模块设计

``Dew``推荐的项目结构为：

----
X Build Project                 // 构建工程
|- sources                      // 源码目录
|-  |- basics                   // 基础源码，为各服务工程的依赖，要求deploy到Maven仓库
|-  |-  |- parent               // 父工程，所有服务端应用的根POM
|-  |-  |- common               // 公共工程，所有服务端应用的基础依赖
|-  |-  |- common-service       // 公共服务工程，所有服务工程的根POM，自身依赖于common
|-  |-  |- <...>                // 其它基础工程，比如common-spark，大数据服务的基础依赖
|-  |- services                 // 服务源码，对应于一个个微服务
|-  |-  |- <service 1>          // 服务1工程
|-  |-  |- <service ...>        // 其它服务工程
|-  |- sdk                      // SDK源码，如项目需要提供SDK时建立此目录
|-  |-  |- <java>               // Java版本的SDK工程
|-  |-  |- <js>                 // JS版本的SDK工程
|-  |-  |- <rest>               // REST版本的SDK工程
|-  |-  |- <...>                // 其它语言版本的SDK工程
|-  |- terminals                // 终端源码
|-  |-  |- <android>            // Android APP工程
|-  |-  |- <ios>                // IOS APP工程
|-  |-  |- <wechat>             // Wechat工程
|-  |-  |- <...>                // 其它终端工程
|- docs                         // 文档工程，所有团队共同维护，Asciidoc方案，后文会介绍
|-  |- src
|-  |-  |- main
|-  |-  |-  |- asciidoc
|-  |-  |-  |-  |- book.adoc    // 文档主目录
|-  |-  |-  |-  |- <...>        // 分模块建立不同的文档文件
|-  |-  |- resources            // 文档引用资源目录，如图片、CSS
|-  |-  |-  |- images
|-  |-  |-  |-  |- <...>
|-  |-  |- pom.xml              // 文档工程使用Maven管理
|-  |-  |- .gitignore
|- env                          // 环境配置工程，以Spring Cloud Config为例，配置存放于Git
|-  |- application.yml
|-  |- <...>
|-  |- .gitignore
|- pom.xml                      // 构建工程的POM
|- .gitmodules                  // Git子模块定义，所有工程都注册到此文件中
|- .gitignore
|- README.adoc                  // 构建工程使用说明
----

推荐各工程使用独立Git库，详见： https://gudaoxuri.gitbook.io/microservices-architecture/wei-fu-wu-hua-zhi-kai-fa-yu-ce-shi/code-managerment[微服务架构设计-代码管理]

==== 代码包设计

``Dew``推荐的包结构为：

----
|- X service
|-  |- src
|-  |-  |- main
|-  |-  |-  |- java
|-  |-  |-  |-  |- src
|-  |-  |-  |-  |-  |- x.y.z
|-  |-  |-  |-  |-  |-  |- XApplication <1>
|-  |-  |-  |-  |-  |-  |- XConfig <2>
|-  |-  |-  |-  |-  |-  |- XInitiator <3>
|-  |-  |-  |-  |-  |-  |- controller
|-  |-  |-  |-  |-  |-  |-  |- EventController <4>
----
<1>	XApplication : 服务启动类
<2>	XConfig：当前服务的配置文件（Spring Cloud格式）
<3>	XInitiator：当前服务启动初始化器，原则上所有与数据库、缓存、定时任务相关的初始化操作都应该从此类发起，以方便排错
<4>	EventController：事件处理器，名称可以更具象，原则上所有与MQ receive相关的操作都被视为交互接口，应该放到controller包下

    .示例
    ----
    @PostConstruct
    public void processTodoAddEvent() {
        // 使用Dew的集群MQ功能实现消息点对点接收
        Dew.cluster.mq.response(Constants.MQ_NOTIFY_TODO_ADD, todo -> {
            logger.info("Received add todo event :" + todo);
        });
    }
    ----

==== 开发期服务调用

在 `Spring Cloud` 体系下，服务间调用需要在Kubernetes环境下，这对开发阶段并不友好，可使用如下方案，模拟多个服务间调用。

[source,yml]
----
spring:
  cloud:
    kubernetes:
      ribbon:
        enabled: false # 禁用服务自动发现

<application name>: # 自定义服务列表，使用此功能需要设置 spring.cloud.kubernetes.ribbon.enabled = false
  ribbon:
    listOfServers: <host>:<port>

# e.g.

tracing-invoke2-example:
  ribbon:
    listOfServers: localhost:8082
----

==== 代码质量管理

推荐使用 ``checkstyle`` 管理代码风格，使用方式：

.checkstyle使用
----
# 在Maven中配置自定义的 checkstyle 文件的路径
<properties>
    <checkstyle.config.path>../../checkstyle/checkstyle.xml</checkstyle.config.path>
</properties>

# 使用Maven命令
mvn -P qa compile

# 也可以IDE的checkstyle插件实现
----

==== `@Validated` 注解

* 在Spring Controller类里，`@Validated` 注解初使用会比较不易上手，在此做下总结

. 对于基本数据类型和String类型，要使校验的注解生效，需在该类上方加 `@Validated` 注解
. 对于抽象数据类型，需在形式参数前加``@Validated``注解

TIP: Spring对抽象数据类型校验抛出异常为``MethodArgumentNotValidException``，http状态码为400，对基本数据类型校验抛出异常为``ConstraintViolationException``，http状态码为500，dew对这两种异常做了统一处理，http状态码均返回200，code为400

====  `jackson` 对于 `Java8` 时间转换（ `SpringMVC` 以 `jackson` 接收 `json` 数据）

. 对于 `LocalDateTime` 类型，需在参数上加 `@JsonFormat` 注解，如下：`@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss")`
.  `LocalDate,LocalTime,Instant` 等，无需配置可自行转换

TIP: `jackson` 对于 `LocalDateTime` 类型的支持与其他三种类型不具有一致性，这是 `jackson` 需要优化的一个点

==== 缓存处理

`Spring Cache` 提供了很好的注解式缓存，但默认没有超时，需要根据使用的缓存容器特殊配置

[source,java]
.Redis缓存过期时间设置
----
@Bean
RedisCacheManager cacheManager() {
    final RedisCacheManager redisCacheManager = new RedisCacheManager(redisTemplate);
    redisCacheManager.setUsePrefix(true);
    redisCacheManager.setDefaultExpiration(<过期秒数>);
    return redisCacheManager;
}
----

==== jdbc 批量插入性能问题

如果不开启rewriteBatchedStatements=true，那么jdbc会把批量插入当做一行行的单条处理，也就没有达到批量插入的效果

[source,java]
.jdbc配置示例
----
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/dew?useUnicode=true&characterEncoding=utf-8&rewriteBatchedStatements=true
    username: root
    password: 123456
----
