[[framework-user-manual]]
=== 框架使用手册

NOTE: ``Dew`` 框架部分是对 ``Spring Boot/Cloud`` 的扩展，使用之前务必了解相关框架的基础知识。

IMPORTANT: 本手册只介绍 ``Dew`` 框架部分的扩展功能！

[[framework-user-manual-import]]
==== 引入方式

----
此章节关联示例:examples/bone-example
----

`Dew` 所有模块均为Maven结构，使用如下：

[source,xml]
----
<!--引入Dew父依赖，也可以使用import方式-->
<parent>
    <groupId>ms.dew</groupId>
    <artifactId>parent-starter</artifactId>
    <!--生产环境请选择合适的版本!-->
    <version>${dew.version}</version>
</parent>
...
<dependencies>
    <!--引入需要的模块-->
    <dependency>
        <groupId>ms.dew</groupId>
        <artifactId>对应模块名，见下文</artifactId>
    </dependency>
</dependencies>
...
<!--开发者介绍-->
<developers>
    <developer>
        <name>...</name>
        <email>...</email>
    </developer>
</developers>
<!--SCM信息-->
<scm>
    <connection>...</connection>
    <developerConnection>...</developerConnection>
    <url></url>
</scm>
...
----

TIP: ``parent-starter`` 中已包含各模块的版本，引用模块依赖时可省略版本号。

.功能模块

|===
|模块名                |核心功能

| parent-starter      | 父Pom模块
| boot-starter        | 核心模块，包含Spring Boot Web相关依赖
| cloud-starter       | Cloud模块，包含Spring Cloud Kuberenetes相关依赖
| cluster-common      | 集群能力接口
| cluster-hazelcast   | Hazelcast集群能力实现
| cluster-rabbit      | RabbitMQ集群能力实现
| cluster-redis       | Redis集群能力实现
| cluster-mqtt        | MQTT集群能力实现
| hbase-starter       | HBase Spring Boot 实现
| idempotent-starter  | 幂等处理模块
| notification        | 通知处理模块
|===

==== Dew类介绍

``Dew``类包装了一些常用的功能，是Dew的能力的主要输出口。

[source,java]
.``Dew``功能说明
----
// 获取集群操作能力，见下文
Dew.cluster.xx
// 获取通知操作能力，见下文
Dew.notify.xx
// 获取Spring上下文
Dew.applicationContext.xx
// 获取Dew配置，说见 框架配置速查
Dew.dewConfig.xx
// 获取认证处理能力，见下文
Dew.auth.xx

//  ============ 获取请求上下文信息  ============
// 当次请求的ID
Dew.context().getId()
// 请求来源IP
Dew.context().getSourceIP()
// 请求最初的URL
Dew.context().getRequestUri()
// 请求对应的token，详见下文
Dew.context().getToken()
// 请求对应的操作者信息，详见下文
Dew.context().optInfo()

// ============ 获取当前组件基础信息 ============
// 应用名称，对应为 spring.application.name
Dew.Info.name
// 应用环境，对应为 spring.profiles.active
Dew.Info.profile
// 应用主机Web端口，对应为 server.port
Dew.Info.webPort
// 应用主机IP
Dew.Info.ip
// 应用主机Host
Dew.Info.host
// 应用实例，各组件实例唯一
Dew.Info.instance

// ============ 定时任务操作 ============
// 此类下的操作会自动带入Dew.context()
/**
* 设定一个周期性调度任务.
*
* @param initialDelaySec 延迟启动的秒数
* @param periodSec       周期调度秒数
* @param fun             调度方法
*/
Dew.Timer.periodic(long initialDelaySec, long periodSec, VoidExecutor fun)
/**
* 设定一个定时任务.
*
* @param delaySec 延迟启动的秒数
* @param fun      定时任务方法
*/
Dew.Timer.timer(long delaySec, VoidExecutor fun)

// ============ 常用工具 ============
/**
* 获取真实IP.
*
* @param request 请求信息
* @return 真实的IP
*/
Dew.Util.getRealIP(HttpServletRequest request)
**
* 获取真实IP.
*
* @param requestHeader     请求头信息
* @param defaultRemoteAddr 缺省的IP地址
* @return 真实的IP
*/
Dew.Util.getRealIP(Map<String, String> requestHeader, String defaultRemoteAddr)
/**
* 创建一个新的线程.
* <p>
* 自动带入Dew.context()
*
* @param fun 执行的方法
*/
Dew.Util.newThread(Runnable fun)

/**
* 统一异常处理.
* <p>
* 封装任意异常到统一的格式，见下文
*
* @param <E>            上抛的异常类型
* @param code           异常编码
* @param ex             上抛的异常对象
* @param customHttpCode 自定义Http状态码
* @return 上抛的异常对象
*/
Dew.E.e(String code, E ex, int customHttpCode)
----

==== 常用工具集

``Dew`` 的常用工具由 ``Dew-Common`` 包提供（ https://github.com/gudaoxuri/dew-common ），功能如下：

. Json与Java对象互转，支持泛型
. Java Bean操作，Bean复制、反射获取/设置注解、字段、方法等
. Java Class扫描操作，根据注解或名称过滤
. Shell脚本操作，Shell内容获取、成功捕获及进度报告等
. 安全（加解密、信息摘要等）操作，Base64、MD5/BCrypt/AES/SHA等对称算法和RSA等非对称算法
. Http操作，包含Get/Post/Put/Delete/Head/Options/Patch操作
. 金额操作，金额转大写操作
. 通用拦截器栈，前/后置、错误处理等
. 定时器操作，定时和周期性任务
. 常用文件操作，根据不同情况获取文件内容、Glob匹配等
. 常用字段操作，各类字段验证、身份证提取、UUID创建等
. 常用时间处理，常规时间格式化模板
. 主流文件MIME整理，MIME分类
. 服务降级处理
. 脚本处理
. 响应处理及分页模型

[source,java]
.``Dew Common`` 的使用
----
// Dew Common 功能均以 $ 开始，如:

//Json转成Java对象:
$.json.toObject(json,JavaModel.class)
//Json字符串转成List对象
$.json.toList(jsonArray, JavaModel.class)
//Bean复制
$.bean.copyProperties(ori, dist)
//获取Class的注解信息
$.bean.getClassAnnotation(IdxController.class, TestAnnotation.RPC.class)
//非对称加密
$.encrypt.Asymmetric.encrypt(d.getBytes("UTF-8"), publicKey, 1024, "RSA")
//Http Get
$.http.get("https://httpbin.org/get")
//验证手机号格式是否合法
$.field.validateMobile("18657120000")
//...
----

TIP: 完整使用手册见 https://gudaoxuri.github.io/dew-common/

[[framework-user-manual-cluster]]
==== 集群功能

----
此章节关联示例:cluster-example
----

`Dew` 的集群支持 `分布式缓存` `分布式Map` `分布式锁` `MQ` `领导者选举`，
并且做了接口抽象以适配不同的实现，目前支持 `Redis` `Hazelcast` `Rabbit` 。

各实现对应的支持如下：

|====
|功能        |Redis   |Hazelcast  |Rabbit | MQTT

|分布式缓存    | *       |           |    |
|分布式Map    |*        |*          |    |
|分布式锁     |*        |*          |    |
|MQ          |*        |*          |*    |*(只支持pub-sub)
|领导者选举   |*        |           |    |
|====

[IMPORTANT]
.各实现的差异
=====
* Redis实现了所有功能，但其MQ上不适用于高可用场景
* 只有Rabbit的MQ支持跟踪日志（见跟踪日志章节）
* MQTT多用于IoT环境
=====

===== 启用方式

[source,xml]
.依赖
----
<dependency>
    <groupId>ms.dew</groupId>
    <artifactId>boot-starter</artifactId>
</dependency>
<!--引入集群依赖，可选redis/hazelcast/rabbit-->
<dependency>
    <groupId>ms.dew</groupId>
    <artifactId>cluster-spi-redis</artifactId>
</dependency>
<dependency>
    <groupId>ms.dew</groupId>
    <artifactId>cluster-spi-hazelcast</artifactId>
</dependency>
<dependency>
    <groupId>ms.dew</groupId>
    <artifactId>cluster-spi-rabbit</artifactId>
</dependency>
<dependency>
    <groupId>ms.dew</groupId>
    <artifactId>cluster-spi-mqtt</artifactId>
</dependency>
----

[source,yml]
.增加配置
----
dew:
    cluster:                            # 集群功能
        cache:                          # 分布式缓存实现，默认为 redis
        map:                            # 分布式Map实现，默认为 redis
        lock:                           # 分布式锁实现，默认为 redis
        mq:                             # MQ实现，默认为 redis
        election:                       # 领导者选举实现，默认为 redis

spring:
    redis:
        host:                           # redis主机
        port:                           # redis端口
        database:                       # redis数据库
        password:                       # redis密码
        lettuce:
          pool:                         # 连接池配置
    rabbitmq:
      host:                             # rabbit主机
      port:                             # rabbit端口
      username:                         # rabbit用户名
      password:                         # rabbit密码
      virtual-host:                     # rabbit VH
    hazelcast:
        addresses: []                   # hazelcast地址，端口可选
dew:
  mw:                                   # 中间件
    mqtt:                               # MQTT集群实现
      broker:                           # Broker地址，e.g. tcp://127.0.0.1:1883
      clientId: Dew_Cluster_<Cluster.instanceId>
                                        # 连接客户端ID，注意一个集群内客户端ID必须唯一
      persistence:                      # 存储，默认为File，可选 memory
      userName:                         # 用户名
      password:                         # 密码
      timeoutSec:                       # 连接超时时间
      keepAliveIntervalSec:             # 心跳间隔时间
      cleanSession: true                # 是否消除Session
----

TIP: 集群服务的使用入口统一为： `Dew.cluster.XX`

===== 分布式缓存

[source,java]
.API
----
include::../../../../../../framework/modules/cluster-common/src/main/java/ms/dew/core/cluster/ClusterCache.java[]
----

[source,java]
.示例
----
// 清空DB
Dew.cluster.cache.flushdb();
// 删除key
Dew.cluster.cache.del("n_test");
// 判断是否存在
Dew.cluster.cache.exists("n_test");
// 设置值
Dew.cluster.cache.set("n_test", "{\"name\":\"jzy\"}", 1);
// 获取值并转成Json
$.json.toJson(Dew.cluster.cache.get("n_test"));
----

TIP: Dew的缓存默认只实现了String、List、Set、Hash等结构常用的、时间复杂度低的操作，
如需要的操作Dew没有提供可使用Spring Boot Data Redis原生的``RedisTemplate<String,String>``

[[framework-user-manual-cluster-redis-mutli-connection]]
.多实例支持

TIP: Redis的Cache实现支持多连接实例，目前只支持Lettuce client。

----
# 配置
spring
    redis:
        host:       # Redis主机
        port:       # Redis端口
        ...
        multi:      # <- 多实例支持
          <key>:    # 实例名称
                    # 可用 Dew.cluster.caches.instance(<key>) 获取
                    # 同时可以用 @Autowired <Key>RedisTemplate 获取Bean
            host:   # Redis主机
            port:   # Redis端口
            ...

# 使用
Dew.cluster.caches.instance("<key>").XXX

# 示例
# 使用key为auth的连接
Dew.cluster.caches.instance("auth").set("token", "xxxxx");
# 使用默认连接
Dew.cluster.cache.set("name", "xxxxx")

----

===== 分布式Map

[source,java]
.API
----
include::../../../../../../framework/modules/cluster-common/src/main/java/ms/dew/core/cluster/ClusterMap.java[]
----

[source,java]
.示例
----
// 创建指定名为test_obj_map的分布Map实例
ClusterMap<TestMapObj> mapObj = Dew.cluster.map.instance("test_obj_map", TestMapObj.class);
// 清空记录
mapObj.clear();
TestMapObj obj = new TestMapObj();
obj.a = "测试";
// 添加一条记录
mapObj.put("test", obj);
// 获取记录
mapObj.get("test");
----

===== 分布式锁

[source,java]
.API
----
include::../../../../../../framework/modules/cluster-common/src/main/java/ms/dew/core/cluster/ClusterLock.java[]
----

[source,java]
.示例
----
// 创建指定名为test_lock的分布锁实例
ClusterLock lock = Dew.cluster.lock.instance("test_lock");
// tryLock 示例，等待0ms，忘了手工unLock或出异常时1s后自动解锁
if (lock.tryLock(0, 1000)) {
    try {
        // 已加锁，执行业务方法
    } finally {
        // 手工解锁
        lock.unLock();
    }
}
// 上面的示例可用 tryLockWithFun 简化
lock.tryLockWithFun(0, 1000, () -> {
    // 已加锁，执行业务方法，tryLockWithFun会将业务方法包裹在try-finally中，无需手工解锁
});
----

===== MQ

[source,java]
.API
----
include::../../../../../../framework/modules/cluster-common/src/main/java/ms/dew/core/cluster/ClusterMQ.java[]
----

[source,java]
.示例
----
// pub-sub
Dew.cluster.mq.subscribe("test_pub_sub", message ->
        logger.info("pub_sub>>" + message.getBody()));
Dew.cluster.mq.publish("test_pub_sub", "msgA",new HashMap<String, Object>() {
      {
          put("h", "001");
      }
  });
Dew.cluster.mq.publish("test_pub_sub", "msgB");
// req-resp
Dew.cluster.mq.response("test_rep_resp", message ->
        logger.info("req_resp>>" + message.getBody()));
Dew.cluster.mq.request("test_rep_resp", "msg1",new HashMap<String, Object>() {
      {
          put("h", "001");
      }
  });
Dew.cluster.mq.request("test_rep_resp", "msg2");
----

IMPORTANT: 发布订阅模式时，发布前 `topic` 必须已经存在，可先使用 `subscribe` 订阅，此操作会自动创建 `topic` 。

TIP: `Rabbit` 实现支持单条 `confirm` 模式。

.MQ的HA功能

MQ的HA（高可用）支持，默认为禁用，可通过``dew.cluster.config.ha-enabled=true``启用。

Dew的MQ仅在数据处理完成后才做commit，这限制了对同一个队列只能串行处理，
MQ的HA开启后，您可以以多线程的方式消费消息，处理过程中如发生服务宕机重启后仍可从未处理完成的消息开始消费。

===== 领导者选举

[source,java]
.API
----
include::../../../../../../framework/modules/cluster-common/src/main/java/ms/dew/core/cluster/ClusterElection.java[]
----

[source,java]
.示例
----
// 实例化fun1类型的领导者选举，Redis的实现支持多类型领导者
ClusterElection electionFun1 = Dew.cluster.election.instance("fun1");
// ...
if (electionFun1.isLeader()) {
   // 当前节点是fun1类型的领导者
   // ...
}
----

==== 统一响应

`Dew` 推荐使用 `协议无关的响应格式`，此格式在 `方法间调用` `非HTTP协议RPC` `MQ` 等数据交互场景做到真正的 `统一响应格式`。
要求返回的格式为``Resp``对象，格式为：

----
{
    "code": "", // 响应编码，与http状态码类似，200表示成功
    "message":"", // 响应附加消息，多有于错误描述
    "body": // 响应正文
}
----

[source,java]
.示例
----
public Resp<String> test(){
    return Resp.success("enjoy!");
    // OR return Resp.notFound("…")/conflict("…")/badRequest("…")/…
}
----

``Resp``类提供了常用操作：详见 https://gudaoxuri.github.io/dew-common/#true-resp[https://gudaoxuri.github.io/dew-common/#true-resp]

``Dew``使用返回格式中的code表示操作状态码，此状态码与HTTP状态码无关，一般情况下HTTP状态码均为200，如需要降级处理时返回500。

[NOTE]
.500 Http状态码说明
====
`500` 状态码仅用于告诉 `Hystrix` 或其它熔断器这次请求是需要降级的错误，对于 `Resp` 中的 `code` 没有影响。

`dew` 框架会把所有 `5xx`（服务端错误，需要降级） 的异常统一转换成 `500` 的Http状态码返回给调用方。

`Resp.xxx.fallback()` 用于显式声明当前返回需要降级，
比如 `Resp.serverError("some message")` 不会降级，返回http状态码为200，body为 `{"code":"500","message":"some message","body":null}`，
但 `Resp.serverError("some message").fallback()` 会降级，返回http状态码为500，body为 同上。
====

===== 消息通知

`Dew` 支持发送消息到钉钉、邮件或自定义HTTP地址，默认支持对未捕获异常及Hystrix错误的通知。

[source,xml]
.通知配置
----
# 格式
dew:
  notifies:
    "": # 通知的标识
      type: DD # 通知的类型，DD=钉钉 MAIL=邮件，邮件方式需要有配置spring.mail下相关的smtp信息 HTTP=自定义HTTP Hook
      defaultReceivers: # 默认接收人列表，钉钉为手机号，邮件为邮箱
      dndTimeReceivers: # 免扰时间内的接收人列表，只有该列表中的接收人才能在免扰时间内接收通知
      args: # 不同类型的参数，邮件不需要设置
        url: # type=DD表示钉钉的推送地址
             # 说明详见：https://open-doc.dingtalk.com/microapp/serverapi2/qf2nxq
             # type=HTTP表示HTTP Hook的地址
        msgType: # 仅用于type=DD，支持 text/markdown            strategy: # 通知策略
        minIntervalSec: 0 # 最小间隔的通知时间，0表示不设置，如为10则表示10s内只会发送一次
        dndTime: # 开启免扰时间，HH:mm-HH:mm 如，18:00-06:00
        forceSendTimes: 3 # 同一免扰周期间通知调用达到几次后强制发送

# 示例
dew:
  notifies:
    __DEW_ERROR__:
      type: DD
      defaultReceivers: xxxx
      args:
        url: https://oapi.dingtalk.com/robot/send?access_token=8ff65c48001c1981df7d3269
      strategy:
        minIntervalSec: 5
    sendMail:
      type: MAIL
      defaultReceivers: x@y.z
    custom:
      type: HTTP
      defaultReceivers: x@y.z
      args:
        url: https://...

----

[source,java]
.通知使用
----
# 最简单的调用
Resp<Void> result = Dew.notify.send("<通知的标识>", "<通知的内容或Throwable>");
# 带通知标题，标题会加上``Dew.Info.instance``
Resp<Void> result = Dew.notify.send("<通知的标识>", "<通知的内容或Throwable>", "<通知标题>");
# 加上特殊接收人列表，非免扰时间内的接收人=配置默认接收人列表+特殊接收人列表，免扰时间内的接收人=配置的免扰时间内的接收人列表
Resp<Void> result = Dew.notify.send("<通知的标识>", "<通知的内容或Throwable>", "<通知标题>", "<特殊接收人列表>");
# 上述三个方法都有异步的重载方法，如
Dew.notify.sendAsync("<通知的标识>", "<通知的内容或Throwable>");
----

[NOTE]
.默认通知标识
====
. 未捕获异常: ``__DEW_ERROR__``，所有未捕获异常（ErrorController）调用此标识发送错误，可通过``dew.basic.format.error-flag`` 修改
. Hystrix错误: ``__HYSTRIX__``，所有Hystrix错误调用此标识发送错误，可通过``dew.cloud.error.notify-flag`` 修改

要启用以上两个通知请确保``dew.notifies``下有相应的配置。
====

[NOTE]
.HTTP自定义通知格式
====
POST请求，Body格式为:

{
    "title": "", // 标题
    "content": "", // 内容
    "receivers": [] // 接收人列表
}

调用正常需要返回200状态码
====

TIP: 消息通知由 ``notification`` 模块提供，``boot-starter`` 集成了此模块，开发中也可以单独引用 ``notification``。

==== 异常处理

`Dew` 会把程序没有捕获的异常统一上抛，同时框架也支持上文统一响应的异常处理：

[source,java]
.自定义异常以支持统一响应API
----
/**
* 统一异常处理.
* <p>
* 封装任意异常到统一的格式，见下文
*
* @param <E>            上抛的异常类型
* @param code           异常编码
* @param ex             上抛的异常对象
* @param customHttpCode 自定义Http状态码
* @return 上抛的异常对象
*/
Dew.E.e(String code, E ex, int customHttpCode)
----

[source,java]
.自定义异常以支持统一响应示例
----
// 业务代码捕获了一个异常
Exception someError = new IOException("xxx不存在")
// 使用统一异常处理封装
throw Dew.E.e("NBE00123",someError,200)
// 请求方得到的结果为 http状态=200，响应体：
{
    "code": "NBE00123",
    "message": "xxx不存在",
    "body": null
}
----

上面介绍的是编码的方式将某些异常封装处理，我们也可以用配置解决：

[source,xml]
.自定义异常配置，启用后此类异常均使用此模块
----
dew:
  basic:
    error-mapping:
      "[<异常类名>]":
        http-code: # http状态码，不存在时使用实例级http状态码
        business-code: # 业务编码，不存在时使用实例级业务编码
        message: # 错误描述，不存在时使用实例级错误描述
----

[source,xml]
.自定义异常配置示例
----
dew:
  basic:
    error-mapping:
      "java.io.IOException":
        http-code: 200
        business-code: "NBE00123"
----

==== 数据验证

``Dew``集成了``Spring validate`` 机制，支持针对 `URL` 及 `Bean` 的验证。

* 在 java bean 中添加各项validation，支持标准``javax.validation.constraints``包下的诸如：`NotNull` ，同时框架扩展了几个检查，如：
   IdNumber、Phone
* 在Controller中添加 `@Validated` 注解 ( Spring还支持@Vaild，但这一注解不支持分组 )
* 支持Spring原生分组校验
* `URL` 类型的验证必须在类头添加 `@Validated` 注解
* `Dew` 框架内置了 `CreateGroup` `UpdateGroup` 两个验证组，验证组仅是一个标识，可为任何java对象

[source,java]
.数据验证示例
----
@RestController
@Api(value = "测试")
@RequestMapping(value = "/test/")
@Validated
public class WebController {

    /**
     * Valid create user dto.
     *
     * @param userDTO the user dto
     * @return the user dto
     */
    @PostMapping(value = "valid-create")
    public UserDTO validCreate(@Validated(CreateGroup.class) @RequestBody UserDTO userDTO) {
        return userDTO;
    }

    /**
     * Valid update user dto.
     *
     * @param userDTO the user dto
     * @return the user dto
     */
    @PostMapping(value = "valid-update")
    public UserDTO validUpdate(@Validated(UpdateGroup.class) @RequestBody UserDTO userDTO) {
        return userDTO;
    }

    /**
     * Valid in method.
     *
     * @param age the age
     * @return the string
     */
    @GetMapping(value = "valid-method-spring/{age}")
    public String validInMethod(@Min(value = 2, message = "age必须大于2") @PathVariable("age") int age) {
        return String.valueOf(age);
    }

    /**
     * Valid in method.
     *
     * @param phone the phone
     * @return the string
     */
    @GetMapping(value = "valid-method-own/{phone}")
    public String validInMethod(@Phone @PathVariable("phone") String phone) {
        return phone;
    }

    public static class UserDTO {

        @NotNull(groups = CreateGroup.class)
        @IdNumber(message = "身份证号错误", groups = {CreateGroup.class, UpdateGroup.class})
        private String idCard;

        @Min(value = 10, groups = {CreateGroup.class, UpdateGroup.class})
        private Integer age;

        @NotNull(groups = CreateGroup.class)
        @Phone(message = "手机号错误", groups = {CreateGroup.class, UpdateGroup.class})
        private String phone;

        // Get & Set ...
    }

}
----

==== CORS支持

[source,yml]
.配置
----
dew:
  security:
    cors:
      allow-origin: # 允许来源，默认 *
      allow-methods: # 允许方法，默认 POST,GET,OPTIONS,PUT,DELETE,HEAD
      allow-headers: # 允许头信息 x-requested-with,content-type
----

[[framework-user-manual-auth]]
==== 权限认证

----
此章节关联示例:auth-example
----

[quote,]
____
支持 `认证缓存` ，即支持将鉴权系统生成的登录信息缓存到业务系统中方便即时调用，并提供三方适配。
____

[source,yml]
.配置认证缓存
----
dew:
  security:
    token-flag: X-Dew-Token             # Token 标识
    token-kind-flag: X-Dew-Token-Kind   # Token类型 标识
    token-in-header: true               # true：token标识在 header 中，反之在url参数中
    token-hash: false                   # Token值是否需要hash，用于解决token值有特殊字符的情况
    router:                             # 路由功能
      enabled: false                    # 是否启用
      black-uri:                        # URL黑名单，支持ant风格
        <Http Method>: [<URLs>]         # URL黑名单列表，Method = all 表示所有方法
      role-auth:                        # 角色认证
        <Role Code>:                    # 角色编码，角色可以带租户，使用.分隔，e.g. tenant1.admin / tenant2.admin
          <Http Method>: [<URLs>]       # 只有该角色才能访问的URL，支持ant风格，支持继承与重写，Method = all 表示所有方法
    token-kinds:                        # Token类型，可为不同的Token类型设置不同的过期时间、保留的版本
      <Kind>:                           # Token类型名称，比如 PC/Android/... ，默认会创建名为 DEFAULT 的类型
        expire-sec: 86400               # Token 过期时间（秒）
        revision-history-limit: 0       # Token 保留的历史版本数量， 0表示不保留历史版本，即有新的登录时会删除此类型下之前所有的Token
----

IMPORTANT: 认证缓存需要 `集群缓存` 服务支持，请引入相关的依赖并配置对应的连接信息等。

[source,java]
.basic 认证缓存接口
----
// 添加登录信息，optInfo封装自鉴权系统过来的登录信息
// 一般在登录认证后操作
Dew.auth.setOptInfo(OptInfo optInfo);
// 获取登录信息，要求在http请求加上token信息
Dew.context().optInfo();
// 删除登录信息
// 一般在注销登录OptInfo后操作
Dew.auth.removeOptInfo();

// 登录信息
public class OptInfo {
    // Token
    String token;
    // 账号编码
    String accountCode;
}
----

TIP: `OptInfo` 为认证缓存信息的基类，使用时可以继承并扩展自己的属性。


IMPORTANT: 使用 `OptInfo` 扩展类型时需要在工程启动时指定扩展类： `DewContext.setOptInfoClazz(<扩展类型>)` 。

[source,java]
.basic 认证缓存示例
----
/**
 * 模拟用户注册.
 */
@PostMapping(value = "user/register")
public Resp<Void> register(@RequestBody User user) {
    // 实际注册处理
    user.setId($.field.createUUID());
    MOCK_USER_CONTAINER.put(user.getId(), user);
    return Resp.success(null);
}

/**
 * 模拟用户登录.
 */
@PostMapping(value = "auth/login")
public Resp<String> login(@RequestBody LoginDTO loginDTO) {
    // 实际登录处理
    User user = MOCK_USER_CONTAINER.values().stream().filter(u -> u.getIdCard().equals(loginDTO.getIdCard())).findFirst().get();
    String token = $.field.createUUID();
    Dew.auth.setOptInfo(new OptInfoExt()
            .setIdCard(user.getIdCard())
            .setAccountCode($.field.createShortUUID())
            .setToken(token)
            .setName(user.getName())
            .setMobile(user.getPhone())
            .setRoleInfo(new HashSet<OptInfo.RoleInfo>() {
                {
                    add(new OptInfo.RoleInfo()
                            .setCode(userDTO.getRole())
                            .setName("..")
                            .setTenantCode("")
                    );
                }
            }));
    return Resp.success(token);
}

/**
 * 模拟业务操作.
 */
@GetMapping(value = "business/someopt")
public Resp<Void> someOpt() {
    // 获取登录用户信息
    Optional<OptInfoExt> optInfoExtOpt = Dew.auth.getOptInfo();
    if (!optInfoExtOpt.isPresent()) {
        return Resp.unAuthorized("用户认证错误");
    }
    // 登录用户的信息
    optInfoExtOpt.get();
    return Resp.success(null);
}

/**
 * 模拟用户注销.
 */
@DeleteMapping(value = "auth/logout")
public Resp<Void> logout() {
    // 实际注册处理
    Dew.auth.removeOptInfo();
    return Resp.success(null);
}
----

上述操作的核心是认证适配器，其接口如下：

[source,java]
.AuthAdapter
----
include::../../../../../../framework/modules/boot-starter/src/main/java/ms/dew/core/auth/AuthAdapter.java[]
----

``Dew`` 默认实现了基于 ``Dew.cluster.cache`` 的适配器以支持上述功能，
对于Redis的Cache实现了 <<framework-user-manual-cluster-redis-mutli-connection>> ，默认优先获取key = ``__auth__`` 的连接配置，不存在时使用默认连接配置。
，项目中也可以实现自己的适配器。

[source,java]
.自定义认证适配器
----
// 自定义适配器
public class CustomAuthAdapter implements AuthAdapter {

 // ...

}

// 注册为Bean（可选，如果自定义适配器用到Spring功能时必须）
@Bean
public CustomAuthAdapter customAuthAdapter() {
    return new CustomAuthAdapter();
}

// 注册自定义适配器
Dew.auth = new CustomAuthAdapter() // 或 Bean实例
----

==== 测试支持

良好的单元测试可以保证代码的高质量，单测的重要原则是内聚、无依赖，好的单测应该是"函数化"的——结果的变化只与传入参数有关。
但实际上我们会的代码往往会与数据库、缓存、MQ等外部工具交互，这会使单测的结果不可控，通常的解决方案是使用Mock，但这无行中引入了单测撰写的成本，
``Dew``使用"内嵌式"工具解决，数据库使用 `H2` ，Redis使用 `embedded redis` ，由于 ``Dew`` 集群的 `Cache` `Map` `Lock` `MQ` 都支持 `Redis` 实现，所以可以做到对主流操作的全覆盖。

[source,xml]
.依赖
----
<dependency>
    <groupId>ms.dew</groupId>
    <artifactId>test-starter</artifactId>
</dependency>
----

[source,yml]
.配置
----
dew:
  cluster: #所有集群操作都使用reids模拟
    cache: redis
    lock: redis
    map: redis
    mq: redis

spring:
  redis:
    host: 127.0.0.1
    port: 6379
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
----

==== 幂等处理

----
此章节关联示例:idempotent-example
----

支持HTTP和非HTTP幂等操作，对于HTTP操作，要求请求方在请求头或URL参数中加上操作ID标识，非HTTP操作由可自由指定操作类型和操作ID标识的来源。

[source,xml]
.依赖
----
<!--引入幂等支持-->
<dependency>
    <groupId>ms.dew</groupId>
    <artifactId>idempotent-starter</artifactId>
</dependency>
----

[source,yml]
.配置
----
dew:
  cluster:
    cache: redis # 启用Redis支持
  idempotent:
    default-expire-ms: 3600000 # 设置默认过期时间，1小时
    default-strategy: item # 设置默认策略，支持 bloom(Bloom Filter)和item(逐条记录)，目前只支持item
    default-opt-id-flag: __IDEMPOTENT_OPT_ID__ # 指定幂等操作ID标识，可以位于HTTP Header或请求参数中
----

[source,java]
.HTTP操作
----
@GetMapping(xxx)
// 启用幂等支持
// 请求头部或参数加上__IDEMPOTENT_OPT_ID__ = xx
@Idempotent
public void test(xxx) {
    // 业务操作
    // ...
    // 业务失败，在保证业务操作的原子性的情况下，在catch中取消幂等，并抛出异常
    DewIdempotent.cancel();
    // 手工确认
    DewIdempotent.confirm();
}
----

``Idempotent``注解说明：

* optIdFlag：指定幂等操作ID标识，可以位于HTTP Header或请求参数中
* expireMs：设置过期时间，单位毫秒
* strategy：设置默认策略
* needConfirm：设置是否需要显式确认，true时，需要进行显式确认操作: ``DewIdempotent.confirm() 或 DewIdempotent.confirm(String optType, String optId)`` 前者要求与请求入口在同一线程中

[source,java]
.非HTTP操作
----
// 初始化类型为transfer_a的幂等操作，需要手工确认，过期时间为1秒
DewIdempotent.initOptTypeInfo("transfer_a", true, 1000, StrategyEnum.ITEM);
// 第一次请求transfer_a类型下的xxxxxxx这个ID，返回不存在，表示可以下一步操作
Assert.assertEquals(StatusEnum.NOT_EXIST, DewIdempotent.process("transfer_a", "xxxxxxx"));
// 第二次请求transfer_a类型下的xxxxxxx这个ID，返回未确认，表示上次操作还在进行中
Assert.assertEquals(StatusEnum.UN_CONFIRM, DewIdempotent.process("transfer_a", "xxxxxxx"));
// 确认操作完成
DewIdempotent.confirm("transfer_a", "xxxxxxx");
// 第三次请求transfer_a类型下的xxxxxxx这个ID，返回已确认，但未过期，仍不能操作
Assert.assertEquals(StatusEnum.CONFIRMED, DewIdempotent.process("transfer_a", "xxxxxxx"));
// 延时1秒
Thread.sleep(1000);
// 再次请求transfer_a类型下的xxxxxxx这个ID，返回不存在（上次请求已过期），表示可以下一步操作
Assert.assertEquals(StatusEnum.NOT_EXIST, DewIdempotent.process("transfer_a", "xxxxxxx"));
----

==== API文档

[source,yml]
.配置
----
dew:
  basic:
    name: # 文档名称
    version: 1.0 # 文档版本
    desc: # 文档说明
    web-site: # 文档站点
    doc:
      base-package: # API文档要扫描的根包，多指定到 Controller 包中
      contact: # 联系人信息，可为空
        name: # 联系人姓名
        url: # 联系人URL
        email: # 联系人邮箱

management: # 文档生成地址前缀为 /management.endpoints.web.base-path
  endpoints:
    web:
      base-path: /management # 可修改成自定义路径，默认为 actuator

----

在线API文档请访问 ``http(s)://<host>:<port>/swagger-ui.html``

离线API文档会生成Asciidoc格式，可通过软件转换成HTML及PDF版本。

[source,txt]
.使用
----
访问任意服务实例:

PUT /{management.endpoints.web.base-path}/doc/offline

{
	"docName":"", # 文档名称
	"docDesc":"", # 文档说明
	"visitUrls":{ # 不同环境的访问地址
		"":""
	},
	"swaggerJsonUrls":[] # swagger.json的URL列表(http://.../v2/api-docs)，可选
}

swaggerJsonUrls 不为空时根据传入的swaggerJsonUrls合成接口文档，为空时分两种情况：

1. 如果是非集群模式（没有注册中心）则只生成本服务的接口文档
2. 如果是集群模式（注册到注册中心）则会合成此集群下所有的接口文档

示例：

{
	"docName":"Dew API 文档",
	"docDesc":"此为Dew的接口文档\n描述可以换行",
	"visitUrls":{
		"开发环境":"http://dev.dew.ecfront.com",
		"测试环境":"http://test.dew.ecfront.com"
	}
}
----

调用此接口后返回Asciidoc格式的文档内容，复制此内容到相应的转换工具中即可生成对应的HTTP或PDF文档。

==== 代码质量检查

``Dew`` 已集成 `Sonar` 插件，只需要在maven中配置 `sonar.host.url` 为目标地址，
然后执行 `mvn clean verify sonar:sonar -P qa -Dsonar.login=<用户名> -Dsonar.password=<密码>` 即可。

TIP: 也可以设置 `sonar.forceAuthentication=false` ，但要注意安全管控。

TIP: 使用 `<maven.test.skip>true</maven.test.skip>` 可跳过特定模块的测试，`<sonar.skip>true</sonar.skip>` 可跳过特定模块的Sonar检查。


===== Spring Boot HBase

在集成 HBase 客户端能力的基础之上，支持 Spring Boot 配置管理、支持 Kerberos 认证。


[source,xml]
.依赖
----
<dependency>
    <groupId>ms.dew</groupId>
    <artifactId>hbase-starter</artifactId>
</dependency>
----

[source,yml]
.配置
----
spring:
  hbase:
    zkQuorum: localhost  # zookeeper url
    znodeParent: /hbase-secure # zookeeper znode parent
    auth:
      type: kerberos # 认证类型，默认是 simple，可选：simple 和 kerberos
      principal: # kerberos 下 principal
      keytab: # kerberos 下 keytab 路径
      hbaseMasterPrincipal: # kerberos 下 hbase master principal
      hbaseRegionServerPrincipal: # kerberos 下 hbase region server principal
      hbaseClientRetriesNumber: # hbase 客户端重试次数，默认：5
      hbaseClientOperationTimeout: # hbase 客户端超时时间，默认：300000
      hbaseClientScannerTimeoutPeriod: # hbase 客户端 scan 超时时间，默认：60000
      hbaseClientPause: # hbase 重试的休眠时间，默认：30
----

[source,java]
.使用
----
@Autowired
private HBaseTemplate hbaseTemplate;

hbaseTemplate.get("table_hbase", "0002093140000000",
                "0", "reg_platform", (result, row) -> Bytes.toString(result.value()));

----

NOTE: HBaseTemplate 其他使用方法可以详见 hbase-starter 模块下的 test 内容。
