=== 使用手册

[IMPORTANT]
.使用申明
====
``Dew``有多个版本通道，使用时请谨慎选择：

. `GA` General Availability，正式版本，通过内部测试没有已知错误并且经过生产验证，生产环境首选！
. `RC` Release Candidate，发行候选版本，通过内部测试没有已知错误，可用于生产环境。
. `Beta` 公开测试版本，没有已知的Major类型Bug，但允许存在个别minor类型Bugs，生产环境使用需要谨慎评估！
. `Alpha` 内部测试版本，很早期的测试版本，未经过内部测试，可能存在较多Bugs，此版本类似技术预览版（Technical Preview），切 *不可* 用于生产环境！
. `SNAPSHOT` 快照版本，类似Nightly版本，更新频繁此不保证质量，切 *不可* 用于生产环境！
====

NOTE: `Dew` 框架是对 ``Spring Boot/Cloud`` 的扩展，使用之前务必了解相关框架的基础知识。

IMPORTANT: 本手册只介绍``Dew``扩展的功能！

==== 结构说明

----
此章节关联示例:bone-example
----

`Dew` 所有模块均为Maven结构，使用如下：

[source,xml]
----
<!--引入Dew父依赖，也可以使用import方式-->
<parent>
    <groupId>com.tairanchina.csp.dew</groupId>
    <artifactId>parent-starter</artifactId>
    <!--生产环境请选择合适的版本!!!!!!!!-->
    <version>${dew.version}</version>
</parent>
...
<dependencies>
    <!--引入需要的模块-->
    <dependency>
        <groupId>com.tairanchina.csp.dew</groupId>
        <artifactId><模块名></artifactId>
    </dependency>
</dependencies>
...
<!--开发者-->
<developers>
    <developer>
        <name></name>
        <email></email>
    </developer>
</developers>
<!--SCM信息-->
<scm>
    <connection></connection>
    <developerConnection></developerConnection>
    <url></url>
</scm>
----

TIP: ``parent-starter`` 中已包含各模块的版本，引用模块依赖时可省略版本号。

``Dew``推荐的代码结构为：

----
|- common-service
|   |- src
|   |   |- main
|   |   |   |- java
|   |   |   |   |- src
|   |   |   |   |   |- x.y.z
|   |   |   |   |   |   |- XApplication <1>
|   |   |   |   |   |   |- XConfig <2>
|   |   |   |   |   |   |- XInitiator <3>
----
<1>	XApplication : 服务启动类
<2>	XConfig：当前服务的配置文件（Spring Cloud格式）
<3>	XInitiator：当前服务启动初始化器，原则上所有初始化操作都应该从此类发起，如初始化脚本、定时任务等，以方便排错

==== 功能模块

|===
|模块名 |核心功能

|`parent-starter` |Dew的工程父依赖
|`boot-starter` |基于Spring Boot的扩展，Dew的核心模块
|`cloud-starter` |基于Spring Cloud的扩展
|`idempotent-starter` |幂性处理模块
|`cluster-common` |集群能力接口
|`cluster-redis` |集群能力-Redis实现
|`cluster-hazelcast` |集群能力-Hazelcast实现
|`cluster-rabbit` |集群能力-Rabbit实现
|`test-starter` |Dew的单元测试封装
|`config` |统一配置中心组件
|`auth` |多租户的权限组件（Scala语言编写）
|`<x>-example` |各类示例
|===

==== 核心功能

===== 常用工具集

``Dew`` 框架的常用工具由 ``Dew-Common`` 包提供（ https://github.com/gudaoxuri/dew-common ），功能如下：

. Json与Java对象互转，支持泛型
. Java Bean操作，Bean复制、反射获取/设置注解、字段、方法等
. Java Class扫描操作，根据注解或名称过滤
. Shell脚本操作，Shell内容获取、成功捕获及进度报告等
. 加解密操作，Base64、MD5/BCrypt/SHA等对称算法和RSA等非对称算法
. Http操作，包含Get/Post/Put/Delete/Head/Options操作
. 金额操作，金额转大写操作
. 通用拦截器栈，前/后置、错误处理等
. 定时器操作，定时和周期性任务
. 常用文件操作，根据不同情况获取文件内容
. 常用字段操作，各类字段验证、身份证提取、UUID创建等
. 常用时间处理，常规时间格式化模板
. 主流文件MIME整理，MIME分类
. 响应处理及分页模型

[TIP]
.``Dew Common`` 的使用
====
``Dew Common`` 功能均以``$``开始，比如:

* Json转成Java对象: `$.json.toObject(json,JavaModel.class)`
* Json字符串转成List对象: `$.json.toList(jsonArray, JavaModel.class)`
* Bean复制：`$.bean.copyProperties(ori, dist)`
* 获取Class的注解信息: `$.bean.getClassAnnotation(IdxController.class, TestAnnotation.RPC.class)`
* 非对称加密: `$.encrypt.Asymmetric.encrypt(d.getBytes("UTF-8"), publicKey, 1024, "RSA")`
* Http Get: `$.http.get("https://httpbin.org/get")`
* 验证手机号格式是否合法: `$.field.validateMobile("18657120000")`
* ...
====

TIP: 完整使用手册见 https://gudaoxuri.github.io/dew-common/

===== 集群功能

----
此章节关联示例:cluster-example
----

`Dew` 的集群支持 `分布式缓存` `分布式Map` `分布式锁` `MQ` `领导者选举`，
并且做了接口抽象以适配不同的实现，目前支持 `Redis` `Hazelcast` `Rabbit` `Eureka` 。

各实现对应的支持如下：

|====
|功能|Redis|Hazelcast|Rabbit

|分布式缓存 | * | / | /
|分布式Map |*|*|/
|分布式锁|*|*|/
|MQ|*|*|*
|领导者选举|*|/|/
|====

[NOTE]
.各实现的差异
=====
* Redis实现了所有功能，但其MQ上不适用于高可靠场景
* 只有Rabbit的MQ支持跟踪日志（见跟踪日志章节）
=====

====== 使用

[source,xml]
.依赖
----
<dependency>
    <groupId>com.tairanchina.csp.dew</groupId>
    <artifactId>boot-starter</artifactId>
</dependency>
<!--引入集群依赖，可选redis/hazelcast/rabbit/eureka-->
<dependency>
    <groupId>com.tairanchina.csp.dew</groupId>
    <artifactId>cluster-spi-redis</artifactId>
</dependency>
<dependency>
    <groupId>com.tairanchina.csp.dew</groupId>
    <artifactId>cluster-spi-hazelcast</artifactId>
</dependency>
<dependency>
    <groupId>com.tairanchina.csp.dew</groupId>
    <artifactId>cluster-spi-rabbit</artifactId>
</dependency>
----

[source,yml]
.增加配置
----
dew:
    cluster: # 集群功能
        cache: # 分布式缓存实现，默认为 redis
        map: # 分布式Map实现，默认为 redis
        lock: # 分布式锁实现，默认为 redis
        mq: # MQ实现，默认为 redis
        election: # 领导者选举实现，默认为 redis

spring:
    redis:
        host: # redis主机
        port: # redis端口
        database: # redis数据库
        password: # redis密码
        pool: # 连接池配置
    rabbitmq:
      host: # rabbit主机
      port: # rabbit端口
      username: # rabbit用户名
      password: # rabbit密码
      virtual-host: # rabbit VH
    hazelcast:
        addresses: [] # hazelcast地址，端口可选
----

集群服务的使用入口统一为： `Dew.cluster.XX`

====== 分布式缓存

TIP: 接口见：com.tairanchina.csp.dew.core.cluster.ClusterCache

[source,java]
.示例
----
Dew.cluster.cache.flushdb();
Dew.cluster.cache.del("n_test");
assert !Dew.cluster.cache.exists("n_test");
Dew.cluster.cache.set("n_test", "{\"name\":\"jzy\"}", 1);
assert Dew.cluster.cache.exists("n_test");
assert "jzy".equals($.json.toJson(Dew.cluster.cache.get("n_test")).get("name").asText());
Thread.sleep(1000);
assert !Dew.cluster.cache.exists("n_test");
assert null == Dew.cluster.cache.get("n_test");
----

TIP: Dew的缓存默认只实现了String、List、Set、Hash等结构常用的，时间复杂度低的操作，
如需要的操作Dew没有提供可使用Spring Boot Data Redis原生的``RedisTemplate<String,String>``

====== 分布式Map

TIP: 接口见：com.tairanchina.csp.dew.core.cluster.ClusterMap

[source,java]
.示例
----
ClusterMap<TestMapObj> mapObj = Dew.cluster.map.instance("test_obj_map", TestMapObj.class);
mapObj.clear();
TestMapObj obj = new TestMapObj();
obj.a = "测试";
mapObj.put("test", obj);
assert "测试".equals(mapObj.get("test").a);
----

====== 分布式锁

TIP: 接口见：com.tairanchina.csp.dew.core.cluster.ClusterLock

[source,java]
.示例
----
// dist lock
ClusterLock lock = Dew.cluster.lock.instance("test_lock");
// tryLock 示例，等待0ms，忘了手工unLock或出异常时1s后自动解锁
if (lock.tryLock(0, 1000)) {
    try {
        // 已加锁，执行业务方法
    } finally {
        // 必须手工解锁
        lock.unLock();
    }
}
// tryLockWithFun 示例
lock.tryLockWithFun(0, 1000, () -> {
    // 已加锁，执行业务方法，tryLockWithFun会将业务方法包裹在try-cache中，无需手工解锁
});
----

====== MQ

TIP: 接口见：com.tairanchina.csp.dew.core.cluster.ClusterMQ

[source,java]
.示例
----
// pub-sub
Dew.cluster.mq.subscribe("test_pub_sub", message ->
        logger.info("pub_sub>>" + message));
Thread.sleep(1000);
Dew.cluster.mq.publish("test_pub_sub", "msgA");
Dew.cluster.mq.publish("test_pub_sub", "msgB");
// req-resp
Dew.cluster.mq.response("test_rep_resp", message ->
        logger.info("req_resp>>" + message));
Dew.cluster.mq.request("test_rep_resp", "msg1");
Dew.cluster.mq.request("test_rep_resp", "msg2");
// rabbit confirm
if (Dew.cluster.mq instanceof RabbitClusterMQ) {
    boolean success = ((RabbitClusterMQ) Dew.cluster.mq).publish("test_pub_sub", "confirm message", true);
    success = ((RabbitClusterMQ) Dew.cluster.mq).request("test_rep_resp", "confirm message", true);
}
----

IMPORTANT: 发布订阅模式时，发布前 `topic` 必须已经存在，可先使用 `subscribe` 订阅，此操作会自动创建 `topic` 。

TIP: `Rabbit` 实现支持单条 `confirm` 模式。

.MQ的HA功能

MQ的HA（高可用）支持，默认MQ启用HA（可通过``dew.cluster.config.ha-enabled=false``关闭）。
可实现。

Dew的MQ仅在数据处理完成后才做commit，这限制了对同一个队列只能串行处理，
MQ的HA开启后，您可以以多线程的方式消费消息，处理过程中如发生服务宕机重启后仍可从未处理完成的消息开始消费。

====== 领导者选举

TIP: 接口见：com.tairanchina.csp.dew.core.cluster.ClusterElection

[source,java]
.示例
----
// 实例化fun1类型的领导者选举，Redis的实现支持多类型领导者
ClusterElection electionFun1 = Dew.cluster.election.instance("fun1");
// ...
if (electionFun1.isLeader()) {
   // 当前节点是fun1类型的领导者
   // ...
}
----

===== 统一响应

`Dew` 推荐使用 `协议无关的响应格式`，此格式在 `方法间调用` `非HTTP协议RPC` `MQ` 等数据交互场景做到真正的 `统一响应格式`。
要求返回的格式为``Resp``对象，格式为：

----
{
    code: "", // 响应编码，与http状态码类似，200表示成功
    message:"", // 响应附加消息，多有于错误描述
    body: // 响应正文
}
----

[source,java]
.示例
----
public Resp<String> test(){
    return Resp.success("enjoy!");
    // or return Resp.notFound("…")/conflict("…")/badRequest("…")/…
}
----

``Resp``类提供了常用操作：详见 https://gudaoxuri.github.io/dew-common/#true-resp[https://gudaoxuri.github.io/dew-common/#true-resp]

``Dew``使用返回格式中的code表示操作状态码，此状态码与HTTP状态码无关，一般情况下HTTP状态码均为200，如需要降级处理时返回500。

[NOTE]
.500 Http状态码说明
====
`500` 状态码仅用于告诉 `Hystrix` 这次请求是需要降级的错误，对于 `Resp` 中的 `code` 没有影响。

`dew` 框架会把所有 `5xx`（服务端错误，需要降级） 的异常统一转换成 `500` 的Http状态码返回给调用方。

`Resp.xxx.fallback()` 用于显示声明当前返回需要降级，
比如 `Resp.serverError("some message")` 不会降级，返回http状态码为200，body为 `{"code":"500","message":"some message","body":null}`，
但 `Resp.serverError("some message").fallback()` 会降级，返回http状态码为500，body为 同上。
====

===== 消息通知

`Dew` 支持发送消息到钉钉或邮件，默认支持对未捕获异常及Hystrix错误的通知。

[source,xml]
.通知配置
----
# 格式
dew:
    notifies:
        "": # 通知的标识
            type: DD # 通知的类型，DD=钉钉 MAIL=邮件，邮件方式需要有配置spring.mail下相关的smtp信息 HTTP=自定义HTTP Hook
            defaultReceivers: # 默认接收人列表，钉钉为手机号，邮件为邮箱
            dndTimeReceivers: # 免扰时间内的接收人列表，只有该列表中的接收人才能在免扰时间内接收通知
            args: # 不同类型的参数，邮件不需要设置
                url: # 钉钉及自定义HTTP的推送地址，钉钉URL说明详见：https://open-doc.dingtalk.com/docs/doc.htm?spm=a219a.7629140.0.0.karFPe&treeId=257&articleId=105735&docType=1
            strategy: # 通知策略
                minIntervalSec: 0 # 最小间隔的通知时间，0表示不设置，如为10则表示10s内只会发送一次
                dndTime: # 开启免扰时间，HH:mm-HH:mm 如，18:00-06:00
                forceSendTimes: 3 # 同一免扰周期间通知调用达到几次后强制发送

# 示例
dew:
  notifies:
    __DEW_ERROR__:
      type: DD
      defaultReceivers: xxxx
      args:
        url: https://oapi.dingtalk.com/robot/send?access_token=8ff65c48001c1981df7d3269
      strategy:
        minIntervalSec: 5
    sendMail:
      type: MAIL
      defaultReceivers: x@y.z
    custom:
      type: HTTP
      defaultReceivers: x@y.z
      args:
        url: https://...

----

[source,java]
.通知使用
----
# 最简单的调用
Resp<Void> result = Dew.notify.send("<通知的标识>", "<通知的内容或Throwable>");
# 带通知标题，标题会加上``Dew.Info.instance``
Resp<Void> result = Dew.notify.send("<通知的标识>", "<通知的内容或Throwable>", "<通知标题>");
# 加上特殊接收人列表，非免扰时间内的接收人=配置默认接收人列表+特殊接收人列表，免扰时间内的接收人=配置的免扰时间内的接收人列表
Resp<Void> result = Dew.notify.send("<通知的标识>", "<通知的内容或Throwable>", "<通知标题>", "<特殊接收人列表>");
# 上述三个方法都有异步的重载方法，如
Dew.notify.sendAsync("<通知的标识>", "<通知的内容或Throwable>");
----

[NOTE]
.默认通知标识
====
. 非捕获异常: ``__DEW_ERROR__``，所有非捕获异常（ErrorController）调用此标识发送错误，可通过``dew.basic.format.error-flag`` 修改
. Hystrix错误: ``__HYSTRIX__``，所有Hystrix错误调用此标识发送错误，可通过``dew.cloud.error.notify-flag`` 修改

要启用以上两个通知请确保``dew.notifies``有相应的配置。
====

[NOTE]
.HTTP自定义通知格式
====
POST请求，Body格式为:

{
    "title": "", // 标题
    "content": "", // 内容
    "receivers": [] // 接收人列表
}

调用正常需要返回200状态码
====

===== 异常处理

`Dew` 会把程序没有捕获的异常统一上抛，同时框架提供了常用的异常检查：

[source,java]
.异常检查，异常类型要求为RuntimeException及其子类
----
Dew.E.check(VoidPredicate notExpected, E ex)
Dew.E.check(boolean notExpected, E ex)
Dew.E.checkNotEmpty(Map<?, ?> objects, E ex)
Dew.E.checkNotEmpty(Iterable<?> objects, E ex)
Dew.E.checkNotNull(Object obj, E ex)
----

[source,xml]
.自定义异常配置，启用后此类异常均使用此模块
----
dew:
  basic:
    error-mapping:
      "[<异常类名>]":
        http-code: # http状态码，不存在时使用实例级http状态码
        business-code: # 业务编码，不存在时使用实例级业务编码
        message: # 错误描述，不存在时使用实例级错误描述
----

===== 数据验证

``Dew``集成了``Spring validate`` 机制，支持针对 `URL` 及 `Bean` 的验证。

* 在 java bean 中添加各项validation，支持标准`javax.validation.constraints`包下的诸如：`NotNull` ，同时框架扩展了几个检查，如：
   IdNumber、Phone
* 在Controller中添加 `@Validated` 注解 ( Spring还支持@Vaild，但这一注解不支持分组 )
* 支持Spring原生分组校验
* `URL` 类型的验证必须在类头添加 `@Validated` 注解
* `Dew` 框架内置了 `CreateGroup` `UpdateGroup` 两个验证组，验证组仅是一个标识，可为任何java对象


===== CORS支持

[source,yml]
.配置
----
dew:
  security:
    cors:
      allow-origin: # 允许来源，默认 *
      allow-methods: # 允许方法，默认 POST,GET,OPTIONS,PUT,DELETE,HEAD
      allow-headers: # 允许头信息 x-requested-with,content-type
----

===== 权限认证

----
此章节关联示例:auth-example
----

[quote,]
____
支持`认证缓存`，即支持将鉴权系统生成的登录信息缓存到业务系统中方便即时调用，并提供三方适配。
____

[source,yml]
.配置认证缓存
----
dew:
    security:
        token-flag: # token key的名称
        token-in-header: # token key是否在http header中，为false是会从url query中获取
        token-hash: # token 值是否做hash（MD5）处理
----

IMPORTANT: 认证缓存需要 `集群缓存` 服务支持，请引入相关的依赖并配置对应的连接信息等。

[source,java]
.basic 认证缓存接口
----
// 添加登录信息，optInfo封装自鉴权系统过来的登录信息
// 一般在登录认证后操作
Dew.auth.setOptInfo(OptInfo optInfo);
// 获取登录信息，要求在http请求加上token信息
Dew.context().optInfo();
// 删除登录信息
// 一般在注销登录后操作
Dew.auth.removeOptInfo();

// 登录信息
public class OptInfo {
    // Token
    String token;
    // 账号编码
    String accountCode;
}
----

TIP: `OptInfo` 为认证缓存信息的基类，使用时可以继承并扩展自己的属性。

IMPORTANT: 使用 `OptInfo` 扩展类型时需要在工程启动时指定扩展类： `DewContext.setOptInfoClazz(<扩展类型>)` 。

[source,java]
.basic 认证缓存示例
----
/**
 * 模拟用户注册
 */
@PostMapping(value = "user/register")
public Resp<Void> register(@RequestBody User user) {
    // 实际注册处理
    user.setId($.field.createUUID());
    MOCK_USER_CONTAINER.put(user.getId(), user);
    return Resp.success(null);
}

/**
 * 模拟用户登录
 */
@PostMapping(value = "auth/login")
public Resp<String> login(@RequestBody LoginDTO loginDTO) {
    // 实际登录处理
    User user = MOCK_USER_CONTAINER.values().stream().filter(u -> u.getIdCard().equals(loginDTO.getIdCard())).findFirst().get();
    String token = $.field.createUUID();
    Dew.auth.setOptInfo(new OptInfoExt()
            .setIdCard(user.getIdCard())
            .setAccountCode($.field.createShortUUID())
            .setToken(token)
            .setName(user.getName())
            .setMobile(user.getPhone()));
    return Resp.success(token);
}

/**
 * 模拟业务操作
 */
@GetMapping(value = "business/someopt")
public Resp<Void> someOpt() {
    // 获取登录用户信息
    Optional<OptInfoExt> optInfoExtOpt = Dew.auth.getOptInfo();
    if (!optInfoExtOpt.isPresent()) {
        return Resp.unAuthorized("用户认证错误");
    }
    // 登录用户的信息
    optInfoExtOpt.get();
    return Resp.success(null);
}

/**
 * 模拟用户注销
 */
@DeleteMapping(value = "auth/logout")
public Resp<Void> logout() {
    // 实际注册处理
    Dew.auth.removeOptInfo();
    return Resp.success(null);
}
----

===== 测试支持

良好的单元测试可以保证代码的高质量，单测的重要原则是内聚、无依赖，好的单测应该是"函数化"的——结果的变化只与传入参数有关。
但实际上我们会的代码往往会与数据库、缓存、MQ等外部工具交互，这会使单测的结果不可控，通常的解决方案是使用Mock，但这无行中引入了单测撰写的成本，
``Dew``使用"内嵌式"工具解决，数据库使用 `H2` ，Redis使用 `embedded redis` ，由于 ``Dew`` 集群的 `Cache` `Map` `Lock` `MQ` 都支持 `Redis` 实现，所以可以做到对主流操作的全覆盖。

[source,xml]
.依赖
----
<dependency>
    <groupId>com.tairanchina.csp.dew</groupId>
    <artifactId>test-starter</artifactId>
</dependency>
----

[source,yml]
.配置
----
dew:
  cluster: #所有集群操作都使用reids模拟
    cache: redis
    lock: redis
    map: redis
    mq: redis

spring:
  redis:
    host: 127.0.0.1
    port: 6379
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
----

===== 幂等处理

----
此章节关联示例:idempotent-example
----

支持HTTP和非HTTP幂等操作，对于HTTP操作，要求请求方在请求头或URL参数中加上操作ID标识，非HTTP操作由可自由指定操作类型和操作ID标识的来源。

[source,xml]
.依赖
----
<!--引入幂等支持-->
<dependency>
    <groupId>com.tairanchina.csp.dew</groupId>
    <artifactId>idempotent-starter</artifactId>
</dependency>
----

[source,yml]
.配置
----
dew:
  cluster:
    cache: redis # 启用Redis支持
  idempotent:
    default-expire-ms: 3600000 # 设置默认过期时间，1小时
    default-strategy: item # 设置默认策略，支持 bloom(Bloom Filter)和item(逐条记录)，目前只支持item
    default-opt-id-flag: __IDEMPOTENT_OPT_ID__ # 指定幂等操作ID标识，可以位于HTTP Header或请求参数中
----

[source,java]
.HTTP操作
----
@GetMapping(xxx)
// 启用幂等支持
// 请求头部或参数加上__IDEMPOTENT_OPT_ID__ = xx
@Idempotent
public void test(xxx) {
    // 业务操作
    // ...
    // 业务失败，在保证业务操作的原子性的情况下，在catch中取消幂等，并抛出异常
    DewIdempotent.cancel();
    // 手工确认
    DewIdempotent.confirm();
}
----

``Idempotent``注解说明：

* optIdFlag：指定幂等操作ID标识，可以位于HTTP Header或请求参数中
* expireMs：设置过期时间，单位毫秒
* strategy：设置默认策略
* needConfirm：设置是否需要显式确认，true时，需要进行显式确认操作: ``DewIdempotent.confirm() 或 DewIdempotent.confirm(String optType, String optId)`` 前者要求与请求入口在同一线程中

[source,java]
.非HTTP操作
----
// 初始化类型为transfer_a的幂等操作，需要手工确认，过期时间为1秒
DewIdempotent.initOptTypeInfo("transfer_a", true, 1000, StrategyEnum.ITEM);
// 第一次请求transfer_a类型下的xxxxxxx这个ID，返回不存在，表示可以下一步操作
Assert.assertEquals(StatusEnum.NOT_EXIST, DewIdempotent.process("transfer_a", "xxxxxxx"));
// 第二次请求transfer_a类型下的xxxxxxx这个ID，返回未确认，表示上次操作还在进行中
Assert.assertEquals(StatusEnum.UN_CONFIRM, DewIdempotent.process("transfer_a", "xxxxxxx"));
// 确认操作完成
DewIdempotent.confirm("transfer_a", "xxxxxxx");
// 第三次请求transfer_a类型下的xxxxxxx这个ID，返回已确认，但未过期，仍不能操作
Assert.assertEquals(StatusEnum.CONFIRMED, DewIdempotent.process("transfer_a", "xxxxxxx"));
// 延时1秒
Thread.sleep(1000);
// 再次请求transfer_a类型下的xxxxxxx这个ID，返回不存在（上次请求已过期），表示可以下一步操作
Assert.assertEquals(StatusEnum.NOT_EXIST, DewIdempotent.process("transfer_a", "xxxxxxx"));
----

=== 工程化

===== API文档

用于生成Asciidoc格式的离线API文档，可通过软件转换成HTML及PDF版本。

[source,yml]
.配置
----
dew:
  basic:
    name: # 文档名称
    version: 1.0 # 文档版本
    desc: # 文档说明
    web-site: # 文档站点
    doc:
        base-package: # API文档要扫描的根包，多指定到 Controller 包中
        contact: # 联系人信息，可为空
            name: # 联系人姓名
            url: # 联系人URL
            email: # 联系人邮箱

management: # 文档生成地址前缀为 /management.context-path
  security:
    enabled: false # 建议关闭管理功能的安全认证
  context-path: /management-admin # 建议修改此前缀以便在网关上统一过滤管理请求
----

[source,txt]
.使用
----
访问任意服务实例:

PUT /{management.context-path}/doc/offline

{
	"docName":"", # 文档名称
	"docDesc":"", # 文档说明
	"visitUrls":{ # 不同环境的访问地址
		"":""
	},
	"swaggerJsonUrls":[] # swagger.json的URL列表(http://.../v2/api-docs)，可选
}

swaggerJsonUrls 不为空时根据传入的swaggerJsonUrls合成接口文档，为空时分两种情况：

1. 如果是非集群模式（没有注册中心）则只生成本服务的接口文档
2. 如果是集群模式（注册到注册中心）则会合成此集群下所有的接口文档

示例：

{
	"docName":"Dew API 文档",
	"docDesc":"此为Dew的接口文档\n描述可以换行",
	"visitUrls":{
		"开发环境":"http://dev.dew.ecfront.com",
		"测试环境":"http://test.dew.ecfront.com"
	}
}
----

调用此接口后返回Asciidoc格式的文档内容，复制此内容到相应的转换工具中即可生成对应的HTTP或PDF文档。

===== 代码质量检查

``Dew`` 已集成 `Sonar` 插件，只需要在maven中配置 `sonar.host.url` 为目标地址，
然后执行 `mvn clean verify sonar:sonar -P qa -Dsonar.login=<用户名> -Dsonar.password=<密码>` 即可。

TIP: 也可以设置 `sonar.forceAuthentication=false` ，但要注意安全管控。

TIP: 使用 `<maven.test.skip>true</maven.test.skip>` 可跳过特定模块的测试，`<sonar.skip>true</sonar.skip>` 可跳过特定模块的Sonar检查。

===== 降级通知

----
此章节关联 `hystrix-example` 示例
----

NOTE: 为能更及时的对服务异常做出处理， `dew` 增加邮件通知功能。

[source,yml]
----
# 通知条件配置示例
dew:
  cloud:
    error:
      enabled: true
      notify-event-types: FAILURE,SHORT_CIRCUITED,TIMEOUT,THREAD_POOL_REJECTED,SEMAPHORE_REJECTED
      notify-include-keys: ["ExampleClient#deleteExe(int,String)","ExampleClient#postExe(int,String)"]

# 邮箱配置示例
spring:
  mail:
    host: smtp.163.com
    username: <邮件地址>
    password: <password为smtp授权码，非邮箱密码>
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
----

==== 跟踪日志

----
此章节关联 `tracing-invokeX-example` 示例
----

用于记录 `服务API调用` （追踪）日志到 `Jaeger`。

NOTE: 此功能由Devops流程涉及的Kubernetes环境自动完成。



