[[dew-2-migration-guide]]
=== Dew 2.x Migration guide

本手册适用于从原生 Spring Cloud 项目及 Dew 1.x 项目迁移到 Dew 2.x 的操作说明。

==== 初始准备

[options="interactive"]

* [ ] 使用 ``dew-devops.sh`` 初始化集群并创建项目

  curl -O https://raw.githubusercontent.com/gudaoxuri/dew/master/devops/sh/dew-devops.sh
  sh dew-devops.sh
  # 选择对应操作，根据提示操作即可
  # 选择 1 进行集群初始化
  # 选择 2 安装 Gitlab runner
  # 选择 3 创建项目：为项目创建namespace、ingress、拉取镜像的secret；对应的 Harbor 账户和镜像仓库等
+
TIP: 如使用Jenkins进行部署，可跳过选项2，详见：<<dew-jenkins-pipeline,Dew Jenkins Pipeline 部署>>

- dew-devops.sh 2.0.x 到 Dew 2.1.X 的变更记录
** 支持不同 profile 使用相同的 harbor project +
   namespace 由<profile>-<project>组成，如果 profile 为空，namespace 为<project>
** 支持更新已存在的 namespace 下的 secret/dew-registry
** 创建 harbor project的时候，可选是否把project进行公开

TIP: 因 Dew DevOps 2.0.x 到 2.1.X 的变更，原有namespace下的 secret/dew-registry 需要手动更新，并在 harbor 上创建对应的project。

[[dew-spring-cloud-config]]
* [ ] 安装并设置Spring Cloud Config

  # 添加helm库
  helm repo add helm-dew-spring-cloud-config https://raw.githubusercontent.com/gudaoxuri/dew/master/devops/chart/dew-spring-cloud-config/
  # 安装，注意域名要能被Kubernetes Pod访问
  helm install helm-dew-spring-cloud-config/dew-spring-cloud-config --name dew-spring-cloud-config --namespace devops \
      --set ingress.hosts={config.dew.ms}
  # 修改配置，修改后需要删除Pod以实现重启获取最新配置
  kubectl -n devops edit cm custom-config
  # e.g.
  # spring:
  #   cloud:
  #     config:
  #       server:
  #         git:
  #           uri: https://gitlab.dew.ms/env/dew.git
  #           username: cdman
  #           password: cdman123
  #   security:
  #     user:
  #       name: dew
  #       password: dew!123456
  #
  # encrypt:
  #   key: dsffjs%^skeSfS@#

==== 迁移步骤

[options="interactive"]

* [ ] [Spring Boot] Spring boot 1.x 迁移到 Spring boot 2.x

  # @see https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0-Migration-Guide

  ######################### 特别注意 ########################

  # 关系型数据库连接池默认由Tomcat改为Hikari，对应的配置示例：
  spring:
    datasource:
      url: jdbc:mysql://...
      username: ...
      password: "{cipher}..."
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        ...
  # MySQL默认的client升级到8.x 注意时区设置及驱动名变更(com.mysql.cj.jdbc.Driver)

  # Hikari连接池 datetime类型有时间差问题，解决方案如下：
    1. 在URL配置中加上 useTimezone=true&serverTimezone=GMT%2B8(推荐使用这种)
    2. 或者修改数据库time_zone

  # Redis的客户端默认由Jedis改为Lettuce，对应的配置示例：
  redis:
    host: ...
    port: 6379
    password: "{cipher}..."
    database: 1
    lettuce:
      pool:
        max-active: 200
        max-wait: 300
        max-idle: 50
        min-idle: 10

  # tomcat容器配置由http变更为servelet，对应的配置示例如下：
  spring:
    servlet:
      multipart:
        enabled: true
        max-file-size: 100MB
        max-request-size: 100MB

  # actuators被重构，修改见：https://www.baeldung.com/spring-boot-actuators

  # Cache不再支持Guava，替换为Caffeine，见： https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-caching.html#boot-features-caching-provider-caffeine

  # 配置值不能为空，e.g.
  csp:
    sdk:
      basic:
        app-secret: "{cipher}..."
        token-expire-ms:  # 错误，值不能为空

  # 使用Springboot定时任务需要在启动类上加上@EnableScheduling


* [ ] [Dew Framework] 修改 ``dew-parent`` 的版本号到最新版本
* [ ] [Dew Framework] 使用IDE全局查询替换 ``com.tairanchina.csp.dew`` 为 ``ms.dew``
* [ ] [Dew Framework] 鉴权修改，详见 <<devops-best-practices-auth,鉴权处理>>
* [ ] [Dew Framework] dew-common 升级到 1.5.x , 核心方法的异常均改为非受检异常，继承自RuntimeException以方便Stream下使用，业务中部分捕获异常需要修改

  由于Dew 2.x 不推荐引入独立的服务网关，故需要对鉴权做一定的修改 。

* [ ] [Dew DevOps] 删除所有 ``eureka`` / ``zuul`` 相关的配置
* [ ] [Dew DevOps] 服务发现使用 spring-cloud-starter-kubernetes-ribbon ,各服务的服务名为spring.application.name的值。注意服务名为小写。
* [ ] [Dew DevOps] 修改项目中的 ``Spring Cloud Config`` 配置

  spring:
    cloud:
      config:
        uri: # 配置中心的URL（见下文 DevOps实现 说明）, e.g. http://config.dew.ms
        username:  # 配置中心访问用户名
        password:  # 配置中心访问密码
        label:  # 加载的Git分支名

* [ ] [Dew DevOps] 删除或修改 ``logback-spring.xml``

  日志会由fluentd自动收集，一般情况下无需配置 logback-spring.xml
  更改日志级别使用 application-X.yml e.g.
  logging:
    level:
      ROOT: INFO
      ms.dew: DEBUG                       # Dew目录日志配置
      org.springframework.jdbc.core: TRACE# Jdbc目录日志配置

* [ ] [Dew DevOps] 为前端工程添加 ``pom.xml`` ，e.g.

  -----------------
  <project xmlns="http://maven.apache.org/POM/4.0.0"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
      <groupId>ms.dew</groupId>
      <artifactId>parent-starter</artifactId>
      <version>2.0.0-rc</version>
    </parent>
    <groupId>ms.dew.devops.it</groupId>
    <artifactId>todo-frontend</artifactId>
    <packaging>pom</packaging>
    <!-- 如果前端工程是原生NodeJS启动方式，请在pom中添加一下配置，如果前端工程是打包成静态文件的方式则不需要添加 -->
    <!--  默认配置此项的NodeJS项目的端口为3000，如需修改端口，请为该前端模块添加.dew配置文件，并设置app.port为指定值。-->
    <properties>
        <frontend.package.type>NATIVE</frontend.package.type>
    </properties>
    <repositories>
      <repository>
        <id>central</id>
        <url>https://repo.maven.apache.org/maven2</url>
      </repository>
      <repository>
        <id>oss-public</id>
        <url>https://oss.sonatype.org/content/groups/public</url>
      </repository>
      <repository>
        <id>oss-snapshot</id>
        <url>https://oss.sonatype.org/content/repositories/snapshots</url>
        <snapshots>
          <enabled>true</enabled>
          <checksumPolicy>warn</checksumPolicy>
        </snapshots>
      </repository>
    </repositories>
  </project>
  -----------------
  将此工程加入到<modules>中，如果前端工程是原生Node启动方式，在pom的properties中添加属性frontend.package.type为NATIVE

* [ ] [Dew DevOps] 去掉前端编译时的进度条显示

  由于进度条的显示调用了清屏子命令，Dew暂无法处理情况，故有诸如 ``webpack -p --progress --hide-modules`` 时应该去掉 ``-p --progress``

* [ ] [Dew DevOps] 为没有继承 ``parent-starter`` 的工程添加 ``parent-starter`` 模块，以实现DevOps功能，此模块没有任何依赖，故引入不会产生副作用

  <parent>
      <groupId>ms.dew</groupId>
      <artifactId>parent-starter</artifactId>
      <version><最新的版本></version>
  </parent>

* [ ] [Dew DevOps] 项目模块的pom.xml内去除 `spring-boot-maven-plugin` 插件

* [ ] [Dew DevOps] 在项目中添加``.dew``配置，详见 <<devops-configuration-dew,.dew 配置>>

  # 在根目录添加 .dew ，至少添加 使用到的 profile 及 namespace 信息
  # e.g.
  # -----------------
  # 默认通知配置，详见 Dew的通知处理模块
  # 默认为钉钉通知
  notify:
    args:
      # 通知的URL，可自行修改，详见 https://open-doc.dingtalk.com/microapp/serverapi2/qf2nxq
      url: xxx
  profiles:
    test:                 # 环境对应的 profile
      namespace: dew-test # 各环境对应的 namespace 为必填项
      app:
        replicas: 2       # 设置各服务的实例个数，推荐设为 2及2个以上，便于滚动更新时不中断服务
    uat:
      namespace: dew-uat
    prod:
      namespace: dew-prod
  # -----------------
  # （可选）根据实际情况为每个应用添加 .dew 文件以添加各应用的特殊配置

TIP: 各环境 namespace 的值请配置为与 dew-devops.sh 脚本中创建的 project 相同的名称。

* [ ] [Dew DevOps] 若使用 Jenkins Pipeline 部署项目，可在 Jenkins 中创建 Pipeline Job。详细配置方法参见：<<dew-jenkins-pipeline,Dew DevOps : Jenkins Pipeline 部署>>
* [ ] [Dew DevOps] 若使用 Gitlab Runner 部署项目，在项目中添加``.gitlab-ci.yml``配置，详见 <<devops-cicd-gitlab-template,gitlab-ci-template.yml>>， e.g.

  stages:
    - deploy
  cache:
    paths:
      - node_modules/
      - .m2/
  # 测试环境部署
  test deploy:
    stage: deploy
    only:
      - test
    tags:
      - test
    script:
      - mvn -P devops deploy
  # 用户验收/预发环境部署
  uat deploy:
    stage: deploy
    only:
      - uat
    tags:
      - uat
    script:
      - mvn -P devops deploy
  prod deploy: # 生产环境部署
    stage: deploy
    only:
      - prod
    tags:
      - prod
    script:
      - mvn -P devops deploy
