#!/bin/bash

log_path=./logs
profile=default

start(){
    app_code=$1
    if [ -n "$2" ] ; then
        profile=$2
    fi

    start_app=''
    if [ $app_code = 'all' ] ; then
        start_app="\-Ddew.flag=apps_sh"
    else
        start_app="\-Ddew.flag=apps_sh -jar ./$app_code.jar"
    fi

    if [ `(ps -ef |grep "$start_app" ) | grep -v grep | wc -l ` -eq 0 ] ; then
        files=`ls ./apps/`
        for file in $files
        do
            app=`echo $file|cut -d "." -f1`
            if [ $1 = 'all' ] || [ "$1" = $app ]; then
                cd ./apps/$app
                nohup java -Dspring.profiles.active=$profile -Ddew.flag=apps_sh -jar ./$app.jar  > /dev/null &
                echo "Started $app"
                cd ../../
            fi
        done
    else
        echo "Start $app_code fail,App Not Stopped."
    fi
}

stop(){
    app_code=$1
    stop_app=''
    if [ $app_code = 'all' ] ; then
        stop_app="\-Ddew.flag=apps_sh"
    else
        stop_app="\-Ddew.flag=apps_sh -jar ./$app_code.jar"
    fi

    pid=`(ps -ef |grep "$stop_app" ) | grep -v grep | awk '{print $2}'`
    if [ -n "$pid" ] ; then
    	 echo "Stop... $app_code"
    	 kill $pid
    fi
    count=0
    while(true)
    do
    	 if [ `(ps -ef |grep "$stop_app" ) | grep -v grep | wc -l ` -eq 0 ] ; then
    		  echo "Stopped $app_code"
    		  break
    	 fi
    	 if [ $count -eq 50 ] ; then # = 50 sec
    		  echo "Stop $app_code fail,use kill -9"
    		  kill -9 `(ps -ef |grep "$stop_app" ) | grep -v grep | awk '{print $2}'`
    	 fi
    		 sleep 1
    		 let count++
    		 if [ $count -gt 100 ] ; then # > 100 sec
    		  echo "Stop $app_code fail,exit."
    	 	 break
     fi
    done
}

restart(){
    stop $1
    start $1 $2
}

tailf(){
    app_code=$1
	exec tailf -n 500 $log_path/$app_code/out.log
}

trace(){
    inst_code=$1
    cat $log_path/*/out.log | grep "=|$instCode|" | sort -k 3 -t \|
}

deploy(){
    app_code=$1
    if [ -n "$2" ] ; then
        profile=$2
    fi

    stop $app_code

    if [ -d apps/$app_code/ ] ; then
     echo "backup $app_code"
     mkdir -p backup/$app_code/
     tar -czf backup/$app_code/`date +%Y%m%d%H%M%S`.tar.gz -C apps/$app_code ./
     echo "delete $app_code"
     rm -rf apps/$app_code/
    fi

    cp -r prepare/$app_code/* apps/$app_code/
    rm -rf prepare/$app_code/*

    start $app_code
}

show(){
    ps -ef | grep "\-Ddew.flag" | grep -v grep
}

tip(){
    echo "============== [ Dew-Framework ] Deploy Script =============="
    echo ">>  start <app code | all >"
    echo ">>  stop <app code | all >"
    echo ">>  restart <app code | all >"
    echo ">>  tailf <app code>"
    echo ">>  trace <instance code>"
    echo "=============="
    echo ">>  deploy <app code>"
    echo ">>  show"
    echo "======================================================="
    exit 1; 
}

# ============== load ==============

. /etc/profile

if [ $# -eq 0 ] ; then 
 tip
fi

command=$1
args=$2
case $command in
	"start")
	if [ "$args" = "" ] ; then 
     tip
    fi
	start $2 $3 ;;
	"stop")
	if [ "$args" = "" ] ; then 
     tip
    fi
	stop $2 ;;
	"restart")
	if [ "$args" = "" ] ; then 
     tip
    fi
	restart $2 $3 ;;
	"tailf")
	if [ "$args" = "" ] ; then 
     tip
    fi
	tailf $2 ;;
	"trace")
    trace $2 ;;
	"deploy")
	if [ "$args" = "" ] ; then 
     tip
    fi
	deploy $2 $3 ;;
	"show")
	show ;;
	* )
	 tip
esac