{
 "title": "JVM (Micrometer)",
 "description": "Dashboard for Micrometer instrumented applications (Java, Spring Boot, Micronaut)",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "namespace", "query": "label_values(namespace)" },
   {
    "name": "service",
    "query": "label_values({namespace=\"$namespace\"},service)"
   },
   {
    "name": "pod",
    "query": "label_values({namespace=\"$namespace\",service=\"$service\"},pod)"
   },
   {
    "name": "jvm_memory_pool_heap",
    "label": "JVM Memory Pools Heap",
    "query": "label_values(jvm_memory_used_bytes{service=\"$service\", pod=\"$pod\", area=\"heap\"},id)"
   },
   {
    "name": "jvm_memory_pool_nonheap",
    "label": "JVM Memory Pools Non-Heap",
    "query": "label_values(jvm_memory_used_bytes{service=\"$service\", pod=\"$pod\", area=\"nonheap\"},id)"
   }
  ]
 },
 "panels": [
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hikaricp_connections{service=\"$service\", pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Quick Facts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "expr": "process_uptime_seconds{service=\"$service\", pod=\"$pod\"}"
      }
     ]
    },
    {
     "title": "Start time",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
     "format": "dateTimeAsIso",
     "valueName": "current",
     "targets": [
      {
       "expr": "process_start_time_seconds{service=\"$service\", pod=\"$pod\"}*1000"
      }
     ]
    },
    {
     "title": "Heap used",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{service=\"$service\", pod=\"$pod\", area=\"heap\"})*100/sum(jvm_memory_max_bytes{service=\"$service\",pod=\"$pod\", area=\"heap\"})"
      }
     ]
    },
    {
     "title": "Non-Heap used",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{service=\"$service\", pod=\"$pod\", area=\"nonheap\"})*100/sum(jvm_memory_max_bytes{service=\"$service\",pod=\"$pod\", area=\"nonheap\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "I/O Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{service=\"$service\", pod=\"$pod\"}[1m]))",
       "legendFormat": "HTTP"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 5 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{service=\"$service\", pod=\"$pod\", status=~\"5..\"}[1m]))",
       "legendFormat": "HTTP - 5xx"
      }
     ]
    },
    {
     "title": "Duration",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_sum{service=\"$service\", pod=\"$pod\", status!~\"5..\"}[1m]))/sum(rate(http_server_requests_seconds_count{service=\"$service\", pod=\"$pod\", status!~\"5..\"}[1m]))",
       "legendFormat": "HTTP - AVG"
      },
      {
       "expr": "max(http_server_requests_seconds_max{service=\"$service\", pod=\"$pod\", status!~\"5..\"})",
       "legendFormat": "HTTP - MAX"
      }
     ]
    },
    {
     "title": "Utilisation",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "tomcat_threads_busy{service=\"$service\", pod=\"$pod\"} or tomcat_threads_busy_threads{service=\"$service\", pod=\"$pod\"}",
       "legendFormat": "TOMCAT - BSY"
      },
      {
       "expr": "tomcat_threads_current{service=\"$service\", pod=\"$pod\"} or tomcat_threads_current_threads{service=\"$service\", pod=\"$pod\"}",
       "legendFormat": "TOMCAT - CUR"
      },
      {
       "expr": "tomcat_threads_config_max{service=\"$service\", pod=\"$pod\"} or tomcat_threads_config_max_threads{service=\"$service\", pod=\"$pod\"}",
       "legendFormat": "TOMCAT - MAX"
      },
      {
       "expr": "jetty_threads_busy{service=\"$service\", pod=\"$pod\"}",
       "legendFormat": "JETTY - BSY"
      },
      {
       "expr": "jetty_threads_current{service=\"$service\", pod=\"$pod\"}",
       "legendFormat": "JETTY - CUR"
      },
      {
       "expr": "jetty_threads_config_max{service=\"$service\", pod=\"$pod\"}",
       "legendFormat": "JETTY - MAX"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "JVM Heap",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{service=\"$service\", pod=\"$pod\", area=\"heap\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{service=\"$service\", pod=\"$pod\", area=\"heap\"})",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{service=\"$service\", pod=\"$pod\", area=\"heap\"})",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "JVM Non-Heap",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 6 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{service=\"$service\", pod=\"$pod\", area=\"nonheap\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{service=\"$service\", pod=\"$pod\", area=\"nonheap\"})",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{service=\"$service\", pod=\"$pod\", area=\"nonheap\"})",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "JVM Total",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{service=\"$service\", pod=\"$pod\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{service=\"$service\", pod=\"$pod\"})",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{service=\"$service\", pod=\"$pod\"})",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "JVM Process Memory",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 6 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "process_memory_rss_bytes{service=\"$service\", pod=\"$pod\"}",
       "legendFormat": "rss"
      },
      {
       "expr": "process_memory_pss_bytes{service=\"$service\", pod=\"$pod\"}",
       "legendFormat": "pss"
      },
      {
       "expr": "process_memory_swap_bytes{service=\"$service\", pod=\"$pod\"}",
       "legendFormat": "swap"
      },
      {
       "expr": "process_memory_swappss_bytes{service=\"$service\", pod=\"$pod\"}",
       "legendFormat": "swappss"
      },
      {
       "expr": "process_memory_pss_bytes{service=\"$service\", pod=\"$pod\"} + process_memory_swap_bytes{service=\"$service\", pod=\"$pod\"}",
       "legendFormat": "phys (pss+swap)"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "system_cpu_usage{service=\"$service\", pod=\"$pod\"}",
       "legendFormat": "system"
      },
      {
       "expr": "process_cpu_usage{service=\"$service\", pod=\"$pod\"}",
       "legendFormat": "process"
      },
      {
       "expr": "avg_over_time(process_cpu_usage{service=\"$service\", pod=\"$pod\"}[1h])",
       "legendFormat": "process-1h"
      }
     ]
    },
    {
     "title": "Load",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "system_load_average_1m{service=\"$service\", pod=\"$pod\"}",
       "legendFormat": "system-1m"
      },
      {},
      {
       "expr": "system_cpu_count{service=\"$service\", pod=\"$pod\"}",
       "legendFormat": "cpu"
      }
     ]
    },
    {
     "title": "Threads",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_threads_live{service=\"$service\", pod=\"$pod\"} or jvm_threads_live_threads{service=\"$service\", pod=\"$pod\"}",
       "legendFormat": "live"
      },
      {
       "expr": "jvm_threads_daemon{service=\"$service\", pod=\"$pod\"} or jvm_threads_daemon_threads{service=\"$service\", pod=\"$pod\"}",
       "legendFormat": "daemon"
      },
      {
       "expr": "jvm_threads_peak{service=\"$service\", pod=\"$pod\"} or jvm_threads_peak_threads{service=\"$service\", pod=\"$pod\"}",
       "legendFormat": "peak"
      },
      {
       "expr": "process_threads{service=\"$service\", pod=\"$pod\"}",
       "legendFormat": "process"
      }
     ]
    },
    {
     "title": "Thread States",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_threads_states_threads{service=\"$service\", pod=\"$pod\"}",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "Log Events (1m)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 18, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(logback_events_total{service=\"$service\", pod=\"$pod\"}[1m])",
       "legendFormat": "{{level}}"
      }
     ]
    },
    {
     "title": "File Descriptors",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "process_open_fds{service=\"$service\", pod=\"$pod\"}",
       "legendFormat": "open"
      },
      {
       "expr": "process_max_fds{service=\"$service\", pod=\"$pod\"}",
       "legendFormat": "max"
      },
      {
       "expr": "process_files_open{service=\"$service\", pod=\"$pod\"} or process_files_open_files{service=\"$service\", pod=\"$pod\"}",
       "legendFormat": "open"
      },
      {
       "expr": "process_files_max{service=\"$service\", pod=\"$pod\"} or process_files_max_files{service=\"$service\", pod=\"$pod\"}",
       "legendFormat": "max"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Memory Pools (Heap)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "repeat": "persistence_counts",
   "collapsed": true,
   "panels": [
    {
     "title": "$jvm_memory_pool_heap",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 36 },
     "repeat": "jvm_memory_pool_heap",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{service=\"$service\", pod=\"$pod\", id=~\"$jvm_memory_pool_heap\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_memory_committed_bytes{service=\"$service\", pod=\"$pod\", id=~\"$jvm_memory_pool_heap\"}",
       "legendFormat": "commited"
      },
      {
       "expr": "jvm_memory_max_bytes{service=\"$service\", pod=\"$pod\", id=~\"$jvm_memory_pool_heap\"}",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "$jvm_memory_pool_heap",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 36 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{service=\"$service\", pod=\"$pod\", id=~\"$jvm_memory_pool_heap\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_memory_committed_bytes{service=\"$service\", pod=\"$pod\", id=~\"$jvm_memory_pool_heap\"}",
       "legendFormat": "commited"
      },
      {
       "expr": "jvm_memory_max_bytes{service=\"$service\", pod=\"$pod\", id=~\"$jvm_memory_pool_heap\"}",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "$jvm_memory_pool_heap",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 36 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{service=\"$service\", pod=\"$pod\", id=~\"$jvm_memory_pool_heap\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_memory_committed_bytes{service=\"$service\", pod=\"$pod\", id=~\"$jvm_memory_pool_heap\"}",
       "legendFormat": "commited"
      },
      {
       "expr": "jvm_memory_max_bytes{service=\"$service\", pod=\"$pod\", id=~\"$jvm_memory_pool_heap\"}",
       "legendFormat": "max"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Memory Pools (Non-Heap)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "$jvm_memory_pool_nonheap",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 44 },
     "repeat": "jvm_memory_pool_nonheap",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{service=\"$service\", pod=\"$pod\", id=~\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_memory_committed_bytes{service=\"$service\", pod=\"$pod\", id=~\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "commited"
      },
      {
       "expr": "jvm_memory_max_bytes{service=\"$service\", pod=\"$pod\", id=~\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "$jvm_memory_pool_nonheap",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 44 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{service=\"$service\", pod=\"$pod\", id=~\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_memory_committed_bytes{service=\"$service\", pod=\"$pod\", id=~\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "commited"
      },
      {
       "expr": "jvm_memory_max_bytes{service=\"$service\", pod=\"$pod\", id=~\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "$jvm_memory_pool_nonheap",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 44 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{service=\"$service\", pod=\"$pod\", id=~\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_memory_committed_bytes{service=\"$service\", pod=\"$pod\", id=~\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "commited"
      },
      {
       "expr": "jvm_memory_max_bytes{service=\"$service\", pod=\"$pod\", id=~\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "max"
      }
     ]
    }
   ]
  },
  {
   "title": "Garbage Collection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Collections",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 52 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(jvm_gc_pause_seconds_count{service=\"$service\", pod=\"$pod\"}[1m])",
       "legendFormat": "{{action}} ({{cause}})"
      }
     ]
    },
    {
     "title": "Pause Durations",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 52 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(jvm_gc_pause_seconds_sum{service=\"$service\", pod=\"$pod\"}[1m])/rate(jvm_gc_pause_seconds_count{service=\"$service\", pod=\"$pod\"}[1m])",
       "legendFormat": "avg {{action}} ({{cause}})"
      },
      {
       "expr": "jvm_gc_pause_seconds_max{service=\"$service\", pod=\"$pod\"}",
       "legendFormat": "max {{action}} ({{cause}})"
      }
     ]
    },
    {
     "title": "Allocated/Promoted",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 52 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "rate(jvm_gc_memory_allocated_bytes_total{service=\"$service\", pod=\"$pod\"}[1m])",
       "legendFormat": "allocated"
      },
      {
       "expr": "rate(jvm_gc_memory_promoted_bytes_total{service=\"$service\", pod=\"$pod\"}[1m])",
       "legendFormat": "promoted"
      }
     ]
    }
   ]
  },
  {
   "title": "Classloading",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Classes loaded",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 60 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_classes_loaded{service=\"$service\", pod=\"$pod\"} or jvm_classes_loaded_classes{service=\"$service\", pod=\"$pod\"}",
       "legendFormat": "loaded"
      }
     ]
    },
    {
     "title": "Class delta (5m)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 60 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "delta(jvm_classes_loaded{service=\"$service\",pod=\"$pod\"}[5m]) or delta(jvm_classes_loaded_classes{service=\"$service\",pod=\"$pod\"}[5m])",
       "legendFormat": "delta"
      }
     ]
    }
   ]
  },
  {
   "title": "Buffer Pools",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Direct Buffers",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 68 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_buffer_memory_used_bytes{service=\"$service\", pod=\"$pod\", id=\"direct\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_buffer_total_capacity_bytes{service=\"$service\", pod=\"$pod\", id=\"direct\"}",
       "legendFormat": "capacity"
      }
     ]
    },
    {
     "title": "Direct Buffers",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 68 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_buffer_count{service=\"$service\", pod=\"$pod\", id=\"direct\"} or jvm_buffer_count_buffers{service=\"$service\", pod=\"$pod\", id=\"direct\"}",
       "legendFormat": "count"
      }
     ]
    },
    {
     "title": "Mapped Buffers",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 68 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_buffer_memory_used_bytes{service=\"$service\", pod=\"$pod\", id=\"mapped\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_buffer_total_capacity_bytes{service=\"$service\", pod=\"$pod\", id=\"mapped\"}",
       "legendFormat": "capacity"
      }
     ]
    },
    {
     "title": "Mapped Buffers",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 68 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_buffer_count{service=\"$service\", pod=\"$pod\", id=\"mapped\"} or jvm_buffer_count_buffers{service=\"$service\", pod=\"$pod\", id=\"mapped\"}",
       "legendFormat": "count"
      }
     ]
    }
   ]
  },
  {
   "title": "HikariCP Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connections Size",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 66 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "hikaricp_connections{pod=\"$pod\", service=\"$service\"}"
      }
     ]
    },
    {
     "title": "Connections",
     "type": "graph",
     "gridPos": { "h": 8, "w": 20, "x": 4, "y": 66 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "hikaricp_connections_active{pod=\"$pod\", service=\"$service\"}",
       "legendFormat": "Active"
      },
      {
       "expr": "hikaricp_connections_idle{pod=\"$pod\", service=\"$service\"}",
       "legendFormat": "Idle"
      },
      {
       "expr": "hikaricp_connections_pending{pod=\"$pod\", service=\"$service\"}",
       "legendFormat": "Pending"
      }
     ]
    },
    {
     "title": "Connection Timeout Count",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 70 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "hikaricp_connections_timeout_total{pod=\"$pod\", service=\"$service\"}"
      }
     ]
    },
    {
     "title": "Connection Creation Time",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 74 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "hikaricp_connections_creation_seconds_sum{pod=\"$pod\", service=\"$service\"} / hikaricp_connections_creation_seconds_count{pod=\"$pod\", service=\"$service\"}",
       "legendFormat": "Creation Time"
      }
     ]
    },
    {
     "title": "Connection Usage Time",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 74 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "hikaricp_connections_usage_seconds_sum{pod=\"$pod\", service=\"$service\"} / hikaricp_connections_usage_seconds_count{pod=\"$pod\", service=\"$service\"}",
       "legendFormat": "Usage Time"
      }
     ]
    },
    {
     "title": "Connection Acquire Time",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 74 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "hikaricp_connections_acquire_seconds_sum{pod=\"$pod\", service=\"$service\"} / hikaricp_connections_acquire_seconds_count{pod=\"$pod\", service=\"$service\"}",
       "legendFormat": "Acquire Time"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request Count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 67 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "irate(http_server_requests_seconds_count{pod=\"$pod\", service=\"$service\", uri!~\".*actuator.*\"}[5m])",
       "legendFormat": "{{method}} [{{status}}] - {{uri}}"
      }
     ]
    },
    {
     "title": "Response Time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 74 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "irate(http_server_requests_seconds_sum{pod=\"$pod\", service=\"$service\", exception=\"None\", uri!~\".*actuator.*\"}[5m]) / irate(http_server_requests_seconds_count{pod=\"$pod\", service=\"$service\", exception=\"None\", uri!~\".*actuator.*\"}[5m])",
       "legendFormat": "{{method}} [{{status}}] - {{uri}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Tomcat Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Error Count",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 68 },
     "format": "locale",
     "valueName": "current",
     "targets": [
      {
       "expr": "tomcat_global_error_total{pod=\"$pod\", service=\"$service\"}"
      }
     ]
    },
    {
     "title": "Active Sessions",
     "type": "graph",
     "gridPos": { "h": 7, "w": 9, "x": 4, "y": 68 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "tomcat_sessions_active_current{pod=\"$pod\", service=\"$service\"}",
       "legendFormat": "active sessions"
      }
     ]
    },
    {
     "title": "Sent & Recieved Bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 11, "x": 13, "y": 68 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "irate(tomcat_global_sent_bytes_total{pod=\"$pod\", service=\"$service\"}[5m])",
       "legendFormat": "Sent Bytes"
      },
      {
       "expr": "irate(tomcat_global_received_bytes_total{pod=\"$pod\", service=\"$service\"}[5m])",
       "legendFormat": "Recieved Bytes"
      }
     ]
    },
    {
     "title": "Thread Config Max",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 72 },
     "format": "locale",
     "valueName": "current",
     "targets": [
      {
       "expr": "tomcat_threads_config_max{pod=\"$pod\", service=\"$service\"}"
      }
     ]
    },
    {
     "title": "Threads",
     "type": "graph",
     "gridPos": { "h": 7, "w": 13, "x": 0, "y": 75 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "tomcat_threads_current{pod=\"$pod\", service=\"$service\"}",
       "legendFormat": "Current thread"
      },
      {
       "expr": "tomcat_threads_busy{pod=\"$pod\", service=\"$service\"}",
       "legendFormat": "Current thread busy"
      }
     ]
    }
   ]
  },
  {
   "title": "Logback Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 },
   "collapsed": true,
   "panels": [
    {
     "title": "INFO logs",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 69 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "irate(logback_events_total{pod=\"$pod\", service=\"$service\", level=\"info\"}[5m])",
       "legendFormat": "info",
       "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
      }
     ]
    },
    {
     "title": "ERROR logs",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 69 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "irate(logback_events_total{pod=\"$pod\", service=\"$service\", level=\"error\"}[5m])",
       "legendFormat": "error",
       "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
      }
     ]
    },
    {
     "title": "WARN logs",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 76 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "irate(logback_events_total{pod=\"$pod\", service=\"$service\", level=\"warn\"}[5m])",
       "legendFormat": "warn",
       "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
      }
     ]
    },
    {
     "title": "DEBUG logs",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 76 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "irate(logback_events_total{pod=\"$pod\", service=\"$service\", level=\"debug\"}[5m])",
       "legendFormat": "debug",
       "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
      }
     ]
    },
    {
     "title": "TRACE logs",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 76 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "irate(logback_events_total{pod=\"$pod\", service=\"$service\", level=\"trace\"}[5m])",
       "legendFormat": "trace",
       "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
      }
     ]
    }
   ]
  }
 ]
}