==== Dew DevOps 脚本部署

此为Dew DevOps 的脚本 ``dew-devops.sh`` 部署相关说明。集成说明参见： http://doc.dew.ms/#%E9%83%A8%E7%BD%B2%E8%BF%90%E7%BB%B4_devops_chapter[Dew Devops 部署运维]

===== Before Started

环境准备：

. 正常运行的Kubernetes集群
. 安装 Helm
. 可用的 Harbor 镜像仓库
. GitLab 仓库
. MinIO，并创建好对应的 bucket(用于进行Runner的缓存存储)
. DockerD（用于Runner中dew-maven-plugin进行项目镜像的打包上传拉取）

项目准备：

. 在项目代码中添加并配置 ``.dew`` 文件（详见 http://doc.dew.ms/#devops-configuration-dew[.dew 配置详情]）
. 在项目代码中添加并配置 ``.gitlab-ci.yml`` 文件（参考 http://doc.dew.ms/#dew_ci_cd_gitlab_ci_%E5%AE%9E%E7%8E%B0[Gitlab CI 实现]）

===== 使用方式
[source,bash]
----
curl -O https://raw.githubusercontent.com/gudaoxuri/dew/master/devops/sh/dew-devops.sh
sh dew-devops.sh
----

====== 选项介绍

.Init cluster
集群初始化：创建一个用于集群服务发现的 ClusterRole

.Install Gitlab runner
Gitlab runner 安装，用于配合 http://doc.dew.ms/#dew_ci_cd_gitlab_ci_%E5%AE%9E%E7%8E%B0[Gitlab CI]部署项目。
此选项功能：
----
创建一个ConfigMap，用于保存Maven的settings.xml。
创建一个Secret用于保存MinIO的key和secret。若不使用MinIO作为缓存存储，需要自行配置。
安装Gitlab Runner,并生成gitlab-runner/gitlab-runner-helm-installation.sh，以便查看配置。
----
TIP: 若不使用MinIO作为缓存存储，请参考 https://gitlab.com/charts/gitlab-runner/blob/master/values.yaml[Gitlab Runner Chart]自行配置。

> Gitlab Runner 部分配置参数说明：
|===
|配置项 | 说明
|runners.image | runner的默认容器镜像，为了保证能使用最新的Dew DevOps功能，建议使用dewms/devops:latest；或者也可使用基于此镜像的自定义镜像
|runners.tags | 用于Gitlab CI 触发部署的runner的tag，此脚本中，tags和项目的profile保持一致。也可在执行脚本时自行修改。
|runners.env.dew_devops_profile | 此为指定部署项目的profile，默认与runners.tags只保持一致。可在执行脚本时自行修改。
|runners.env.dew_devops_XXX | 更多runner.env配置项，详见：http://doc.dew.ms/#maven_%E9%85%8D%E7%BD%AE[Maven 配置]
|===

.Create a project
创建项目：用于给需要部署的项目来创建一个部署的命名空间等。
详见： http://doc.dew.ms/#%E5%8F%91%E7%94%9F%E4%BA%86%E4%BB%80%E4%B9%88[创建项目]

