== 新手入门

[IMPORTANT]
.使用申明
====
`SNAPSHOT` 版本未经过测试，不得用于生产。
====

====
本章节将以大名鼎鼎的 Pet Store 为例子介绍如何使用此框架。
https://www.google.ca/search?dcr=0&q=pet+store+sample+application&oq=pet+store+sample+application&gs_l=psy-ab.3..0i7i30k1l3.75349.75349.0.75740.1.1.0.0.0.0.388.388.3-1.1.0.foo%2Ccfro%3D1%2Cnso-ehuqi%3D1%2Cnso-ehuui%3D1%2Cewh%3D0%2Cnso-mplt%3D2%2Cnso-enksa%3D0%2Cnso-enfk%3D1%2Cnso-usnt%3D1%2Cnso-qnt-npqp%3D0-1701%2Cnso-qnt-npdq%3D0-54%2Cnso-qnt-npt%3D0-1%2Cnso-qnt-ndc%3D300%2Ccspa-dspm-nm-mnp%3D0-05%2Ccspa-dspm-nm-mxp%3D0-125%2Cnso-unt-npqp%3D0-17%2Cnso-unt-npdq%3D0-54%2Cnso-unt-npt%3D0-0602%2Cnso-unt-ndc%3D300%2Ccspa-uipm-nm-mnp%3D0-007525%2Ccspa-uipm-nm-mxp%3D0-052675...0...1.1.64.psy-ab..0.1.387.w0jrLVcL93k[Pet Store In Google]

本章节的代码见：example/guide-petstore
====

=== 构建一个脚手架工程

* 建立 `guide-petstore` 目录，添加 `pom.xml` 文件，加入如下内容：

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <!--引入Dew父依赖，也可以使用import方式-->
    <parent>
        <groupId>com.ecfront.dew</groupId>
        <artifactId>parent</artifactId>
        <!--生产环境切不可以使用快照版本!!!!!!!!-->
        <version>1.0.0-SNAPSHOT</version>
    </parent>

    <groupId>yourgroup</groupId>
    <artifactId>pet-store</artifactId>
    <packaging>jar</packaging>
    <version>1.0.0</version>

    <dependencies>
        <!--dew的核心包-->
        <dependency>
            <groupId>com.ecfront.dew</groupId>
            <artifactId>boot-core</artifactId>
        </dependency>
        <!--引入集群能力-redis实现-->
        <dependency>
            <groupId>com.ecfront.dew</groupId>
            <artifactId>cluster-spi-redis</artifactId>
        </dependency>
        <!--添加web（spring mvc）功能-->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <!--添加文档支持-->
        <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-swagger2</artifactId>
        </dependency>
        <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-swagger-ui</artifactId>
        </dependency>
        <!--添加spring jdbc template支持-->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-jdbc</artifactId>
        </dependency>
        <!--使用druid连接池-->
        <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>druid-spring-boot-starter</artifactId>
        </dependency>
        <!--测试项目，使用h2数据库-->
        <dependency>
            <groupId>com.h2database</groupId>
            <artifactId>h2</artifactId>
        </dependency>
        <!--引入Dew封装的单元测试功能-->
        <dependency>
            <groupId>com.ecfront.dew</groupId>
            <artifactId>test-starter</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

</project>
----

TIP: `parent` 中已包含各模块的版本，引用模块依赖时可省略版本号。

TIP: `dew` 支持 `Spring boot` 下各类数据持久化框架，此处使用基于 `Spring jdbc template` 封装的轻量实现，此实现对应的连接池必须为 `Druid` 。

* 添加添加文件到 `src/main/resources/application.yml` ，内容如下：

[source,yml]
----
spring:
  application:
    name: pet-store # 项目名称，对Spring Cloud而言也是service-id
  datasource: # 数据库连接信息
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:petstore
  redis: # Redis连接信息
    host: localhost
    port: 6379
    database: 0

server: # http端口号
  port: 8080

dew:
  basic:
    name: pet-store
    version: 1.0
    desc: 宠物商店
    web-site:
    doc:
      base-package: your.group.controller # API文档路径
  cluster:
    cache: redis # 指定集群缓存实现为redis
  jdbc:
    base-packages: ["your.group.jdbc"]
----

* 添加工程启动类

[source,java]
----
/**
 * 工程启动类
 * 重写父类的ComponentScan，先扫描Dew下的包，再是项目的根包
 */
@ComponentScan(basePackageClasses = {Dew.class,PetStoreApplication.class})
public class PetStoreApplication extends DewBootApplication {

    public static void main(String[] args) {
        new SpringApplicationBuilder(PetStoreApplication.class).run(args);
    }

}
----

* 创建其它标准的目录及文件，结果如下：

----
guide-petstore
    |-src
        |-main
            |-java
                |-your
                    \-group
                        \-PetStoreApplication.java
            \-resources
                |-application.yml
                \-logback-spring.xml
        |-test
    |-.gitignore
    |-pom.xml
----

TIP: `.gitignore` 是标准的git忽略文件，`logback-spring.xml` 为 `logback` 在 `spring` 下的配置文件，与项目说明关系不大，详见源代码。

=== 添加数据访问处理

* 添加数据初始化类到 `src/main/java/your/group/PetstoreInitiator.java` ，内容如下：

[source,java]
----
/**
 * 在根路径创建用于初始化数据/行为的类
 * <p>
 * 减少滥用PostConstruct造成的不可控因素
 */
@Component
public class PetstoreInitiator {

    @PostConstruct
    public void init() {
        // 初始宠物表
        Dew.ds().jdbc().execute("CREATE TABLE pet\n" +
                "(\n" +
                "id int primary key auto_increment,\n" +
                "type varchar(50),\n" +
                "price decimal(11,4) not null,\n" +
                "create_time datetime,\n" +
                "update_time datetime,\n" +
                "enabled bool\n" +
                ")");
        // 初始化客户表
        Dew.ds().jdbc().execute("CREATE TABLE customer\n" +
                "(\n" +
                "id int primary key auto_increment,\n" +
                "name varchar(50)\n" +
                ")");
        // 初始化订单表
        Dew.ds().jdbc().execute("CREATE TABLE t_order\n" +
                "(\n" +
                "id int primary key auto_increment,\n" +
                "pet_id int,\n" +
                "customer_id int,\n" +
                "price decimal(11,4) not null,\n" +
                "create_time datetime \n" +
                ")");
    }

}
----

* 添加数据对象到 `src/main/java/your/group/entity` 下，共3个类：

[source,java]
----
@Entity
public class Pet {

    @PkColumn
    private int id;
    @Column(notNull = true)
    private String type;
    @Column(notNull = true)
    private BigDecimal price;
    @CreateTimeColumn
    private Date createTime;
    @UpdateTimeColumn
    private Date updateTime;
    @EnabledColumn
    private boolean enabled;

    // get/set...
}

@Entity
public class Customer {

    @PkColumn
    private int id;
    @Column(notNull = true)
    private String name;

    // get/set...
}

@Entity(tableName = "t_order") // order对象对应的是t_order表
public class Order {

    @PkColumn
    private int id;
    @Column(notNull = true)
    private int petId;
    @Column(notNull = true)
    private int customerId;

    // get/set...
}

----

[TIP]
.注解说明
====
. 表名/字段名在注解中没有特别指定时均以驼峰转下划线规则处理
. `@PkColumn` 标识主键字段，支持int/String类型
. `@Column` 标识普通字段
. `@CreateTimeColumn/@UpdateTimeColumn` 标识创建/更新字段，会自动添加日期
. `@EnabledColumn` 标识状态字段，用于软删除操作
====

* 添加 `DAO` 到 `src/main/java/your/group/jdbc` 下，共3个接口：

[source,java]
----
public interface PetDao extends DewDao<Integer, Pet> {
}

public interface CustomerDao extends DewDao<Integer, Customer> {
}

public interface OrderDao extends DewDao<Integer, Order> {

    @Select(value = "SELECT ord.* FROM t_order ord " +
            "INNER JOIN pet p ON p.id = ord.pet_id " +
            "WHERE ord.customer_id = #{customerId} AND p.type = #{petType}",entityClass = Order.class)
    Page<Order> findOrders(@Param("customerId") int customerId, @Param("petType") String petType,
                           @Param("pageNumber") long pageNumber, @Param("pageSize") int pageSize);

}
----

[TIP]
.DAO说明
====
. `DewDao` 是所有DAO的父类，实现了基础的CRUD方法
. `@Select` 允许自定义查询语句
====

=== 添加逻辑服务

* 添加 `Service` 到 `src/main/java/your/group/service` 下，共3个类：

[source,java]
----
@Service
@CacheConfig(cacheNames = "petstore:pet") // 启用缓存指定key前缀
public class PetService implements CRUSService<PetDao, Integer, Pet> {

    @Override
    @Cacheable // 缓存id对应的内容
    public Resp<Pet> getById(Integer id) {
        return CRUSService.super.getById(id);
    }

    @Override
    @CacheEvict // 清除id对应的内容
    public Resp<Void> disableById(Integer id) {
        return CRUSService.super.disableById(id);
    }

    @Override
    @CachePut("#pet.id") // 添加/更新id对应的内容
    public Resp<Pet> save(Pet pet) {
        return CRUSService.super.save(pet);
    }

    @Override
    @CachePut("#id")// 添加/更新id对应的内容
    public Resp<Pet> updateById(Integer id, Pet pet) {
        return CRUSService.super.updateById(id, pet);
    }
}

@Service
public class CustomerService implements CRUDSService<CustomerDao, Integer, Customer> {
}

@Service
public class OrderService implements CRUService<OrderDao, Integer, Order> {

    // 使用分布式锁
    private ClusterDistLock lock;

    @Autowired
    private PetService petService;

    @PostConstruct
    public void init() {
        // 锁的初始化，写在@PostConstruct方法中
        lock = Dew.cluster.dist.lock("petstore:buy");
    }

    /**
     * 购买方法
     *
     * @return {@link Resp}
     */
    public Resp<Void> buy(int petId, int customerId) {
        Order order = new Order();
        order.setCustomerId(customerId);
        order.setPetId(petId);
        try {
            // 加锁，推荐加上锁过期时间
            if (lock.tryLock(100, 5000)) {
                if (petService.getById(petId).getBody().isEnabled()) {
                    // 只能未被购买的宠物才能购买
                    getDao().insert(order);
                    // 标记宠物已被购买
                    petService.disableById(petId);
                }
            } else {
                return Resp.locked("请求忙，请稍后重试");
            }
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
            return Resp.serverError("未知错误");
        } finally {
            // 解锁，不要忘了
            lock.unLock();
        }
        return Resp.success(null);
    }

    public Resp<Page<Order>> findOrders(int customerId, String petType, long pageNumber, int pageSize) {
        return Resp.success(getDao().findOrders(customerId, petType, pageNumber, pageSize));
    }

}
----

[TIP]
.Service说明
====
框架提供了C(Create)R(Read)U(Update)D(Delete)S(Status,软删除)脚手架，对应于各个服务父类
====

[TIP]
.Resp 响应模型，用于统一请求响应处理
====
模型由三个属性组成：

 * code：响应编码，同HTTP状态码，200表示成功
 * message：错误描述，当code不为200时用于描述错误信息
 * body：返回的实际对象
====

=== 添加Web支持

* 添加 `Service` 到 `src/main/java/your/group/controller` 下，共3个类：

[source,java]
----
@RestController
@RequestMapping("pet/")
@Api(description = "宠物操作")
public class PetController implements CRUSController<PetService, Integer, Pet> {
}

@RestController
@RequestMapping("customer/")
@Api(description = "客户操作")
public class CustomerController implements CRUDController<CustomerService, Integer, Customer> {
}

@RestController
@RequestMapping("order/")
@Api(description = "订单操作")
public class OrderController implements CRUController<OrderService, Integer, Order> {

    @PostMapping("buy")
    @ApiOperation(value = "获取记录分页列表")
    public Resp<Void> buy(@Validated @RequestBody BuyVO buyVO) {
        return getService().buy(buyVO.getPetId(), buyVO.getCustomerId());
    }

    @GetMapping("{type}/{pageNumber}/{pageSize}")
    @ApiOperation(value = "获取记录分页列表")
    public Resp<Page<Order>> findOrders(@PathVariable String type, @RequestParam int customerId, @PathVariable long pageNumber, @PathVariable int pageSize) {
        return getService().findOrders(customerId, type, pageNumber, pageSize);
    }

}
----

[TIP]
.Controller说明
====
* 和Service一样，框架提供了C(Create)R(Read)U(Update)D(Delete)S(Status,软删除)脚手架，对应于各个服务父类
* `@Api` `@ApiOperation` 为 `swagger` 文档的功能
====

=== 开始测试

* 添加 `Test` 到 `src/test/java/your/group/test/PetStoreTest.java` 下，内容如下：

[source,java]
----
@RunWith(SpringRunner.class)
@SpringBootTest(classes = PetStoreApplication.class, webEnvironment = SpringBootTest.WebEnvironment.DEFINED_PORT)
@ComponentScan(basePackageClasses = {Dew.class, PetStoreApplication.class})
public class PetStoreTest {

    private static final String url = "http://127.0.0.1:8080/";

    @Test
    public void testAll() throws Exception {
        // 添加2个宠物
        $.http.post(url+"pet/", "{\"type\":\"dog\",\"price\":1000,\"enabled\":true}");
        $.http.post(url+"pet/", "{\"type\":\"dog\",\"price\":1000,\"enabled\":true}");
        // 添加一个客户
        Customer customer = Resp.generic($.http.post(url+"customer/", "{\"name\":\"张三\"}"), Customer.class).getBody();
        // 查看可购买的宠物列表，有2个
        List<Pet> pets = Resp.genericList($.http.get(url+"pet/?enabled=true"), Pet.class).getBody();
        Assert.assertEquals(2, pets.size());
        // 购买一个宠物
        $.http.post(url+"order/buy", "{\"petId\":\"" + pets.get(0).getId() + "\",\"customerId\":\"" + customer.getId() + "\"}");
        // 查看订单列表
        List<Order> orders = Resp.genericPage($.http.get(url+"order/dog/1/10?customerId=" + customer.getId()), Order.class).getBody().getObjects();
        Assert.assertEquals(1,orders.size());
        Assert.assertEquals(pets.get(0).getId(), orders.get(0).getPetId());
        // 查看可购买的宠物列表，只有1个
        pets = Resp.genericList($.http.get(url+"pet/?enabled=true"), Pet.class).getBody();
        Assert.assertEquals(1, pets.size());
    }

}
----

[TIP]
.测试说明
====
由于引用了

  <groupId>com.ecfront.dew</groupId>
  <artifactId>test-starter</artifactId>

其自带了嵌入式的redis及h2数据库，所以无须第三方依赖即可使用。
====

=== 打包发布

* 提交代码质检

Dew 已集成 `Sonar` 插件，只需要在maven中配置 `sonar.host.url` 为目标地址，然后执行 `mvn clean verify sonar:sonar -P qa` 即可。

* 生成离线API文档

[source,java]
.建立如下测试类
----
@RunWith(SpringRunner.class)
@SpringBootApplication
@SpringBootTest(classes = PetStoreApplication.class, webEnvironment = SpringBootTest.WebEnvironment.DEFINED_PORT)
@ComponentScan(basePackageClasses = {Dew.class, PetStoreApplication.class})
public class DocTest {

    @Test
    public void empty() throws IOException{
            DocProcessor.create($.http.get("http://127.0.0.1:8080/v2/api-docs"));
    }

}
----

`mvn -Dtest=DocTest clean test -P doc`

在项目路径下 `api-docs` 就可以看到生成的文档了。

* 打包

`mvn clean package -P fatjar`

=== Next!

此章节演示了 `Dew` 的基础使用，`Spring Cloud` 相关的内容也未涉及，更多使用请参见 `用户手册` 。
